// Biblioteca pública: solo ingredientes genéricos con su fuente (USDA, CIQUAL 2025 con licencia Etalab 2.0, o estequiometría para aditivos puros).
// Los nombres comerciales y los valores de fichas técnicas van en la biblioteca privada (fuera de este repo).
// estado: "revisado" = ID evaluado y aceptado; "propuesto" = cambio pendiente de aprobación.
window.BIBLIOTECA = [
  {
    nombre: "Ripio de pollo",
    alias: ["pollo solo carne"],
    tipo: "usda",
    fdc: "171052",
    estado: "revisado",
    nota: "Pollo, solo carne, crudo. Se mantiene frente a 171104 (carne mecánicamente deshuesada) por contraste con datos de laboratorio.",
  },
  {
    nombre: "Carne de cerdo magra",
    alias: ["cerdo magro", "carne de cerdo"],
    tipo: "usda",
    fdc: "168220",
    estado: "revisado",
    nota: "Cortes compuestos (pierna, lomo, paleta), solo magro, crudo.",
  },
  {
    nombre: "Sal refinada",
    alias: ["sal"],
    tipo: "usda",
    fdc: "173468",
    estado: "revisado",
  },
  {
    nombre: "Ajo en polvo",
    alias: [],
    tipo: "usda",
    fdc: "171325",
    estado: "revisado",
  },
  {
    nombre: "Cebolla puerro",
    alias: ["puerro"],
    tipo: "usda",
    fdc: "2727584",
    estado: "propuesto",
    nota: "Reemplaza 170005 (cebolla larga, scallions).",
  },
  {
    nombre: "Almidón de yuca",
    alias: ["almidon de yuca", "tapioca"],
    tipo: "usda",
    fdc: "169717",
    estado: "propuesto",
    nota: "Tapioca seca; la ficha del proveedor no trae información nutricional.",
  },
  {
    nombre: "Proteína concentrada de soya",
    alias: ["concentrado de soya", "proteina de soya"],
    tipo: "usda",
    fdc: "172447",
    estado: "propuesto",
    nota: "Concentrado de soya por extracción con alcohol.",
  },
  {
    nombre: "Pulpa de maracuyá",
    alias: [
      "maracuyá",
      "maracuya",
      "pulpa de maracuya",
      "maracuyá con semillas",
    ],
    tipo: "valores",
    ref: "CIQUAL 2025 (13016)",
    valores: {
      hum: 73.6,
      prot: 2.13,
      grasa: 3.0,
      sat: 0.54,
      azt: 8.5,
      fib: 6.8,
      cen: 0.54,
      vita: 84.2,
      vitd: 0.0,
      vitc: 25.6,
      col: 0.0,
      na: 0,
      k: 240.0,
      ca: 8.1,
      zn: 0.76,
      fe: 0.56,
      cu: 0.15,
      mg: 26.0,
      mn: 0.19,
      cho: 20.73,
    },
    estado: "propuesto",
    nota: "CIQUAL 13016: «Fruit de la passion ou maracudja, chair sans peau, avec pépins, cru». Carbohidratos por diferencia; vitamina A en equivalentes de retinol. Valores «<» o «traces» tomados como 0.",
  },
  {
    nombre: "Yuca cocida",
    alias: ["yuca blanca cocida", "mandioca cocida"],
    tipo: "valores",
    ref: "CIQUAL 2025 (54034)",
    valores: {
      hum: 65.2,
      prot: 0.69,
      grasa: 0.043,
      fib: 0.4,
      cen: 0.91,
      vitc: 13.1,
      col: 0.0,
      ca: 12.1,
      zn: 0.35,
      fe: 0.6,
      cu: 0.018,
      mn: 0.038,
      cho: 33.16,
    },
    estado: "propuesto",
    nota: "CIQUAL 54034: «Manioc, racine cuite». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Plátano cocido",
    alias: ["platano cocido"],
    tipo: "valores",
    ref: "CIQUAL 2025 (53101)",
    valores: {
      hum: 67.3,
      prot: 0.79,
      grasa: 0.18,
      sat: 0.069,
      azt: 14.0,
      fib: 2.3,
      cen: 0.58,
      vita: 30.8,
      vitd: 0.0,
      vitc: 10.9,
      col: 0.0,
      na: 5.0,
      k: 465.0,
      ca: 2.0,
      zn: 0.13,
      fe: 0.58,
      cu: 0.066,
      mg: 32.0,
      cho: 31.15,
    },
    estado: "propuesto",
    nota: "CIQUAL 53101: «Banane plantain, cuite». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Árbol del pan cocido",
    alias: ["arbol del pan cocido", "fruta de pan cocida"],
    tipo: "valores",
    ref: "CIQUAL 2025 (20813)",
    valores: {
      hum: 70.5,
      prot: 1.29,
      grasa: 0.11,
      cen: 0.8,
      vitc: 8.17,
      cho: 27.3,
    },
    estado: "propuesto",
    nota: "CIQUAL 20813: «Fruit à pain, chair sans peau, cuit à la vapeur, prélevé à la Martinique». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Ahuyama cocida",
    alias: ["ahuyama cocida al vapor", "zapallo cocido"],
    tipo: "valores",
    ref: "CIQUAL 2025 (20814)",
    valores: {
      hum: 91.8,
      prot: 1.1,
      grasa: 0.097,
      azt: 1.91,
      fib: 2.0,
      cen: 0.46,
      vita: 143.0,
      k: 321.0,
      cho: 6.54,
    },
    estado: "propuesto",
    nota: "CIQUAL 20814: «Giraumon (variété locale), chair sans peau, cuit à la vapeur, prélevé à la Martinique». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Polen fresco",
    alias: ["polen", "polen húmedo", "polen de abejas"],
    tipo: "valores",
    ref: "CIQUAL 2025 (31111)",
    valores: {
      hum: 22.7,
      prot: 17.5,
      grasa: 5.17,
      sat: 1.81,
      azt: 26.8,
      fib: 9.07,
      cen: 3.29,
      vitc: 6.34,
      na: 7.57,
      k: 411.0,
      ca: 105.0,
      zn: 3.95,
      fe: 11.6,
      cu: 0.51,
      mg: 63.3,
      cho: 51.34,
    },
    estado: "propuesto",
    nota: "CIQUAL 31111: «Pollen, frais». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Polen seco",
    alias: ["polen deshidratado", "polen seco de abejas"],
    tipo: "valores",
    ref: "CIQUAL 2025 (31109)",
    valores: {
      hum: 7.58,
      prot: 21.9,
      grasa: 4.2,
      azt: 36.5,
      fib: 11.3,
      cen: 2.63,
      na: 89.8,
      k: 464.0,
      ca: 85.2,
      zn: 5.6,
      cu: 1.95,
      mg: 82.8,
      cho: 63.69,
    },
    estado: "propuesto",
    nota: "CIQUAL 31109: «Pollen, partiellement séché». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Hígado de conejo",
    alias: ["higado de conejo"],
    tipo: "valores",
    ref: "CIQUAL 2025 (40110)",
    valores: {
      hum: 70.8,
      prot: 19.0,
      grasa: 4.0,
      sat: 1.09,
      azt: 3.75,
      fib: 0.0,
      cen: 0.8,
      vita: 4540.0,
      vitc: 9.0,
      col: 263.0,
      na: 69.5,
      k: 335.0,
      ca: 12.3,
      zn: 2.04,
      fe: 6.61,
      cu: 0.81,
      mg: 24.2,
      mn: 0.14,
      cho: 5.4,
    },
    estado: "propuesto",
    nota: "CIQUAL 40110: «Foie, lapin, cru». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  // Aditivos: USDA SR Legacy, USDA Branded (etiqueta) o, en último recurso, estequiometría del compuesto puro.
  {
    nombre: "Goma guar",
    alias: ["goma de algarrobo", "goma garrofin", "goma de semillas"],
    tipo: "usda",
    fdc: "169045",
    estado: "propuesto",
    nota: "SR Legacy «Gums, seed gums (includes locust bean, guar)»: un solo registro para goma guar y goma de algarrobo.",
  },
  {
    nombre: "Pectina",
    alias: ["pectina en polvo", "pectina citrica"],
    tipo: "usda",
    fdc: "168821",
    estado: "propuesto",
    nota: "SR Legacy «Pectin, unsweetened, dry mix».",
  },
  {
    nombre: "Agar",
    alias: ["agar agar", "agar-agar"],
    tipo: "usda",
    fdc: "170090",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Seaweed, agar, dried».",
  },
  {
    nombre: "Gelatina sin sabor",
    alias: ["gelatina sin sabor en polvo", "gelatina en polvo", "grenetina"],
    tipo: "usda",
    fdc: "169599",
    estado: "propuesto",
    nota: "SR Legacy «Gelatins, dry powder, unsweetened» (humedad 13 g, proteína 85,6 g). Su bibliografía usaba Branded 2633150 y 2314166, cuyas etiquetas dan 100 y 111 g de proteína por 100 g.",
  },
  {
    nombre: "Proteína aislada de soya",
    alias: ["aislado de soya", "aislado de proteina de soya"],
    tipo: "usda",
    fdc: "174276",
    estado: "propuesto",
    nota: "SR Legacy «Soy protein isolate».",
  },
  {
    nombre: "Lecitina de soya",
    alias: ["lecitina"],
    tipo: "usda",
    fdc: "171426",
    estado: "propuesto",
    nota: "SR Legacy «Oil, soybean lecithin».",
  },
  {
    nombre: "Bicarbonato de sodio",
    alias: ["bicarbonato"],
    tipo: "usda",
    fdc: "175040",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, baking soda».",
  },
  {
    nombre: "Polvo para hornear",
    alias: ["polvo de hornear"],
    tipo: "usda",
    fdc: "172805",
    estado: "revisado",
    nota: "ID de su bibliografía (SR Legacy, bajo en sodio). SR Legacy trae también 172803 (con sulfato de sodio y aluminio) y 172804 (solo fosfato).",
  },
  {
    nombre: "Cremor tártaro",
    alias: ["bitartrato de potasio"],
    tipo: "usda",
    fdc: "175041",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, cream of tartar». Su bibliografía usaba Branded 2425013, que solo trae potasio.",
  },
  {
    nombre: "Stevia",
    alias: ["estevia", "extracto de stevia"],
    tipo: "usda",
    fdc: "170679",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Sweetener, herbal extract powder from Stevia leaf».",
  },
  {
    nombre: "Levadura seca",
    alias: ["levadura", "levadura seca activa", "levadura instantanea"],
    tipo: "usda",
    fdc: "175043",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Leavening agents, yeast, baker's, active dry».",
  },
  {
    nombre: "Levadura fresca",
    alias: ["levadura prensada"],
    tipo: "usda",
    fdc: "175042",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, yeast, baker's, compressed».",
  },
  {
    nombre: "Vinagre",
    alias: ["vinagre blanco", "vinagre de alcohol"],
    tipo: "usda",
    fdc: "172237",
    estado: "propuesto",
    nota: "SR Legacy «Vinegar, distilled».",
  },
  {
    nombre: "Fécula de maíz",
    alias: ["almidon de maiz", "maicena"],
    tipo: "usda",
    fdc: "169698",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cornstarch».",
  },
  {
    nombre: "Jarabe de glucosa",
    alias: ["glucosa liquida", "jarabe de maiz"],
    tipo: "usda",
    fdc: "168837",
    estado: "propuesto",
    nota: "SR Legacy «Syrups, corn, light».",
  },
  {
    nombre: "Goma xantan",
    alias: ["goma xantana", "xantana", "goma xanthan"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2285516)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 77.8,
      fib: 77.8,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 2890,
      vitc: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 9 g; ingredientes: xanthan gum). Branded no trae humedad ni cenizas. Otra etiqueta de goma xantan pura (2663656) da 10 g de proteína y 0 mg de sodio: los valores varían entre fabricantes.",
  },
  {
    nombre: "Maltodextrina",
    alias: ["maltodextrina de maiz"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2585907)",
    valores: { prot: 0, grasa: 0, cho: 94.6, azt: 3.57, na: 89 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 56 g; ingredientes: maltodextrin). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Dextrosa",
    alias: ["dextrosa monohidratada", "glucosa en polvo"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2412809)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 90,
      fib: 0,
      azt: 90,
      ca: 0,
      fe: 0,
      k: 0,
      na: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 20 g; ingredientes: dextrose). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Eritritol",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2617273)",
    valores: { prot: 0, grasa: 0, cho: 100, azt: 0, na: 0 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 12 g; ingredientes: organic erythritol). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Alulosa",
    alias: ["alulosa en polvo"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2652700)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 100,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      k: 0,
      na: 0,
      vitd: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 10 g; ingredientes: allulose). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Psyllium",
    alias: ["psilio", "cascara de psyllium"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2413270)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 80,
      fib: 80,
      azt: 0,
      ca: 0,
      fe: 0,
      k: 0,
      na: 200,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 5 g; ingredientes: psyllium husk powder). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Sal nitral",
    alias: ["sal de nitro", "sal de cura", "sal curante"],
    tipo: "valores",
    ref: "USDA Branded (ID: 1777297)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 0,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 36200,
      vitc: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 0.8 g; ingredientes: salt, sodium nitrite 6.25%, red fd&c #3 dye 0.000079%). Branded no trae humedad ni cenizas. ID de su bibliografía. El porcentaje de nitrito cambia entre fabricantes: confirmar con la ficha.",
  },
  {
    nombre: "Ácido cítrico",
    alias: ["acido citrico anhidro"],
    tipo: "valores",
    ref: "USDA Branded (ID: 628368)",
    valores: { prot: 0, grasa: 0, cho: 0, na: 0 },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 1 g; ingredientes: citric acid, less than 2% silicon dioxide (anticaking)). Branded no trae humedad ni cenizas. ID de su bibliografía. La etiqueta declara 0 g de carbohidratos.",
  },
  {
    nombre: "Humo líquido",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2082239)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 0,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 0,
      vitc: 0,
      sat: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 4.5 g; ingredientes: water, natural pecan smoke flavor, vinegar, molasses and caramel color). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Glutamato monosódico",
    alias: ["glutamato", "msg"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2449440)",
    valores: { prot: 0, grasa: 0, cho: 0, na: 12500 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 1 g; ingredientes: monosodium glutamate). Branded no trae humedad ni cenizas. Por estequiometría (C5H8NO4Na·H2O) el sodio sería 12 285 mg.",
  },
  {
    nombre: "Almidón de papa",
    alias: ["fecula de papa"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2671914)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 83.3,
      fib: 0,
      azt: 0,
      ca: 17,
      fe: 0,
      k: 58,
      na: 0,
      vitd: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 12 g; ingredientes: potato starch). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Benzoato de sodio",
    alias: ["benzoato"],
    tipo: "valores",
    ref: "Estequiometría: C7H5NaO2 (144,10 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 15954,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 36.77,
      cho: 63.23,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Sorbato de potasio",
    alias: ["sorbato"],
    tipo: "valores",
    ref: "Estequiometría: C6H7KO2 (150,22 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 26028,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 46.0,
      cho: 54.0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como K2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Nitrito de sodio",
    alias: ["nitrito"],
    tipo: "valores",
    ref: "Estequiometría: NaNO2 (69,00 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 33321,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas no estimadas (se descompone al incinerar).",
  },
  {
    nombre: "Metabisulfito de sodio",
    alias: ["metabisulfito"],
    tipo: "valores",
    ref: "Estequiometría: Na2S2O5 (190,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 24188,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 74.72,
      cho: 25.28,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2SO4; carbohidratos por diferencia.",
  },
  {
    nombre: "Propionato de calcio",
    alias: ["propionato"],
    tipo: "valores",
    ref: "Estequiometría: Ca(C3H5O2)2 (186,22 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 21522,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 53.75,
      cho: 46.25,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como CaCO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Lactato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: NaC3H5O3 (112,06 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 20516,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 47.29,
      cho: 52.71,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. El lactato de sodio se vende como solución al 60 %: multiplicar por 0,6 o cargar la ficha.",
  },
  {
    nombre: "Diacetato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: NaH(C2H3O2)2 (142,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 16180,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 37.3,
      cho: 62.7,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Eritorbato de sodio",
    alias: ["eritorbato", "isoascorbato de sodio"],
    tipo: "valores",
    ref: "Estequiometría: C6H7NaO6·H2O (216,12 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 10638,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 24.52,
      cho: 75.48,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. Sin actividad de vitamina C declarada.",
  },
  {
    nombre: "Ascorbato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: C6H7NaO6 (198,11 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 88904,
      col: 0,
      na: 11605,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 26.75,
      cho: 73.25,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Ácido ascórbico",
    alias: ["vitamina c"],
    tipo: "valores",
    ref: "Estequiometría: C6H8O6 (176,12 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 100000,
      col: 0,
      na: 0,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 0,
      cho: 100,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Ácido orgánico: cenizas 0; carbohidratos por diferencia.",
  },
  {
    nombre: "Tripolifosfato de sodio",
    alias: ["tripolisfosfato de sodio", "tripolifosfato", "stpp"],
    tipo: "valores",
    ref: "Estequiometría: Na5P3O10 (367,86 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 31248,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Pirofosfato ácido de sodio",
    alias: ["sapp"],
    tipo: "valores",
    ref: "Estequiometría: Na2H2P2O7 (221,94 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 20718,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 91.88,
      cho: 8.12,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como NaPO3; carbohidratos por diferencia.",
  },
  {
    nombre: "Hexametafosfato de sodio",
    alias: ["hexametafosfato", "shmp"],
    tipo: "valores",
    ref: "Estequiometría: (NaPO3)n (101,96 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 22548,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Citrato de sodio",
    alias: ["citrato trisodico"],
    tipo: "valores",
    ref: "Estequiometría: Na3C6H5O7·2H2O (294,10 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 23451,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 54.06,
      cho: 45.94,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. Dihidrato: el agua de cristalización no sale a 105 °C y queda en los carbohidratos por diferencia.",
  },
  {
    nombre: "Cloruro de potasio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: KCl (74,55 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 52447,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Cloruro de calcio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: CaCl2 anhidro (110,98 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 36113,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Carbonato de calcio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: CaCO3 (100,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 40044,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Agua",
    alias: ["agua potable", "hielo"],
    tipo: "agua",
    estado: "revisado",
  },
];
