// Biblioteca pública: solo ingredientes genéricos con su fuente (USDA, CIQUAL 2025 con licencia Etalab 2.0, o estequiometría para aditivos puros).
// Los nombres comerciales y los valores de fichas técnicas van en la biblioteca privada (fuera de este repo).
// estado: "revisado" = ID evaluado y aceptado; "propuesto" = cambio pendiente de aprobación.
window.BIBLIOTECA = [
  {
    nombre: "Ripio de pollo",
    alias: ["pollo solo carne", "carne de pollo, solo carne"],
    tipo: "usda",
    fdc: "171052",
    estado: "revisado",
    nota: "Pollo, solo carne, crudo. Se mantiene frente a 171104 (carne mecánicamente deshuesada) por contraste con datos de laboratorio.",
  },
  {
    nombre: "Carne de cerdo magra",
    alias: ["cerdo magro", "carne de cerdo"],
    tipo: "usda",
    fdc: "168220",
    estado: "revisado",
    nota: "Cortes compuestos (pierna, lomo, paleta), solo magro, crudo.",
  },
  {
    nombre: "Sal refinada",
    alias: ["sal"],
    tipo: "usda",
    fdc: "173468",
    estado: "revisado",
  },
  {
    nombre: "Ajo en polvo",
    alias: [],
    tipo: "usda",
    fdc: "171325",
    estado: "revisado",
  },
  {
    nombre: "Cebolla puerro",
    alias: ["puerro"],
    tipo: "usda",
    fdc: "2727584",
    estado: "propuesto",
    nota: "Reemplaza 170005 (cebolla larga, scallions).",
  },
  {
    nombre: "Almidón de yuca",
    alias: ["almidon de yuca", "tapioca"],
    tipo: "usda",
    fdc: "169717",
    estado: "propuesto",
    nota: "ID de su bibliografía corregido el 11-sep-2026: su fuente traía 2396508, que es harina de yuca (raíz entera). SR Legacy 169717 «Tapioca, pearl, dry» es almidón.",
  },
  {
    nombre: "Proteína concentrada de soya",
    alias: ["concentrado de soya"],
    tipo: "usda",
    fdc: "172447",
    estado: "propuesto",
    nota: "Concentrado de soya por extracción con alcohol.",
  },
  {
    nombre: "Pulpa de maracuyá con semillas",
    alias: ["maracuya con semillas"],
    tipo: "valores",
    ref: "CIQUAL 2025 (13016)",
    valores: {
      hum: 73.6,
      prot: 2.13,
      grasa: 3.0,
      sat: 0.54,
      azt: 8.5,
      fib: 6.8,
      cen: 0.54,
      vita: 84.2,
      vitd: 0.0,
      vitc: 25.6,
      col: 0.0,
      na: 0,
      k: 240.0,
      ca: 8.1,
      zn: 0.76,
      fe: 0.56,
      cu: 0.15,
      mg: 26.0,
      mn: 0.19,
      cho: 20.73,
    },
    estado: "propuesto",
    nota: "CIQUAL 13016: «Fruit de la passion ou maracudja, chair sans peau, avec pépins, cru». Carbohidratos por diferencia; vitamina A en equivalentes de retinol. Valores «<» o «traces» tomados como 0.",
  },
  {
    nombre: "Yuca cocida",
    alias: ["yuca blanca cocida", "mandioca cocida"],
    tipo: "valores",
    ref: "CIQUAL 2025 (54034)",
    valores: {
      hum: 65.2,
      prot: 0.69,
      grasa: 0.043,
      fib: 0.4,
      cen: 0.91,
      vitc: 13.1,
      col: 0.0,
      ca: 12.1,
      zn: 0.35,
      fe: 0.6,
      cu: 0.018,
      mn: 0.038,
      cho: 33.16,
    },
    estado: "propuesto",
    nota: "CIQUAL 54034: «Manioc, racine cuite». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Plátano cocido",
    alias: ["platano cocido"],
    tipo: "valores",
    ref: "CIQUAL 2025 (53101)",
    valores: {
      hum: 67.3,
      prot: 0.79,
      grasa: 0.18,
      sat: 0.069,
      azt: 14.0,
      fib: 2.3,
      cen: 0.58,
      vita: 30.8,
      vitd: 0.0,
      vitc: 10.9,
      col: 0.0,
      na: 5.0,
      k: 465.0,
      ca: 2.0,
      zn: 0.13,
      fe: 0.58,
      cu: 0.066,
      mg: 32.0,
      cho: 31.15,
    },
    estado: "propuesto",
    nota: "CIQUAL 53101: «Banane plantain, cuite». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Árbol del pan cocido",
    alias: ["arbol del pan cocido", "fruta de pan cocida"],
    tipo: "valores",
    ref: "CIQUAL 2025 (20813)",
    valores: {
      hum: 70.5,
      prot: 1.29,
      grasa: 0.11,
      cen: 0.8,
      vitc: 8.17,
      cho: 27.3,
    },
    estado: "propuesto",
    nota: "CIQUAL 20813: «Fruit à pain, chair sans peau, cuit à la vapeur, prélevé à la Martinique». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Ahuyama cocida",
    alias: ["ahuyama cocida al vapor", "zapallo cocido"],
    tipo: "valores",
    ref: "CIQUAL 2025 (20814)",
    valores: {
      hum: 91.8,
      prot: 1.1,
      grasa: 0.097,
      azt: 1.91,
      fib: 2.0,
      cen: 0.46,
      vita: 143.0,
      k: 321.0,
      cho: 6.54,
    },
    estado: "propuesto",
    nota: "CIQUAL 20814: «Giraumon (variété locale), chair sans peau, cuit à la vapeur, prélevé à la Martinique». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Polen fresco",
    alias: ["polen", "polen húmedo", "polen de abejas"],
    tipo: "valores",
    ref: "CIQUAL 2025 (31111)",
    valores: {
      hum: 22.7,
      prot: 17.5,
      grasa: 5.17,
      sat: 1.81,
      azt: 26.8,
      fib: 9.07,
      cen: 3.29,
      vitc: 6.34,
      na: 7.57,
      k: 411.0,
      ca: 105.0,
      zn: 3.95,
      fe: 11.6,
      cu: 0.51,
      mg: 63.3,
      cho: 51.34,
    },
    estado: "propuesto",
    nota: "CIQUAL 31111: «Pollen, frais». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Polen seco",
    alias: ["polen deshidratado", "polen seco de abejas"],
    tipo: "valores",
    ref: "CIQUAL 2025 (31109)",
    valores: {
      hum: 7.58,
      prot: 21.9,
      grasa: 4.2,
      azt: 36.5,
      fib: 11.3,
      cen: 2.63,
      na: 89.8,
      k: 464.0,
      ca: 85.2,
      zn: 5.6,
      cu: 1.95,
      mg: 82.8,
      cho: 63.69,
    },
    estado: "propuesto",
    nota: "CIQUAL 31109: «Pollen, partiellement séché». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  {
    nombre: "Hígado de conejo",
    alias: ["higado de conejo"],
    tipo: "valores",
    ref: "CIQUAL 2025 (40110)",
    valores: {
      hum: 70.8,
      prot: 19.0,
      grasa: 4.0,
      sat: 1.09,
      azt: 3.75,
      fib: 0.0,
      cen: 0.8,
      vita: 4540.0,
      vitc: 9.0,
      col: 263.0,
      na: 69.5,
      k: 335.0,
      ca: 12.3,
      zn: 2.04,
      fe: 6.61,
      cu: 0.81,
      mg: 24.2,
      mn: 0.14,
      cho: 5.4,
    },
    estado: "propuesto",
    nota: "CIQUAL 40110: «Foie, lapin, cru». Carbohidratos por diferencia; vitamina A en equivalentes de retinol.",
  },
  // Aditivos: USDA SR Legacy, USDA Branded (etiqueta) o, en último recurso, estequiometría del compuesto puro.
  {
    nombre: "Goma guar",
    alias: ["goma de algarrobo", "goma garrofin", "goma de semillas"],
    tipo: "usda",
    fdc: "169045",
    estado: "propuesto",
    nota: "SR Legacy «Gums, seed gums (includes locust bean, guar)»: un solo registro para goma guar y goma de algarrobo.",
  },
  {
    nombre: "Pectina",
    alias: ["pectina en polvo", "pectina citrica"],
    tipo: "usda",
    fdc: "168821",
    estado: "propuesto",
    nota: "SR Legacy «Pectin, unsweetened, dry mix».",
  },
  {
    nombre: "Agar",
    alias: ["agar agar", "agar-agar"],
    tipo: "usda",
    fdc: "170090",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Seaweed, agar, dried».",
  },
  {
    nombre: "Gelatina sin sabor",
    alias: ["gelatina sin sabor en polvo", "gelatina en polvo", "grenetina"],
    tipo: "usda",
    fdc: "169599",
    estado: "propuesto",
    nota: "SR Legacy «Gelatins, dry powder, unsweetened» (humedad 13 g, proteína 85,6 g). Su bibliografía usaba Branded 2633150 y 2314166, cuyas etiquetas dan 100 y 111 g de proteína por 100 g.",
  },
  {
    nombre: "Proteína aislada de soya",
    alias: ["aislado de soya", "aislado de proteina de soya", "proteina de soya"],
    tipo: "usda",
    fdc: "174276",
    estado: "propuesto",
    nota: "SR Legacy «Soy protein isolate».",
  },
  {
    nombre: "Lecitina de soya",
    alias: ["lecitina"],
    tipo: "usda",
    fdc: "171426",
    estado: "propuesto",
    nota: "SR Legacy «Oil, soybean lecithin».",
  },
  {
    nombre: "Bicarbonato de sodio",
    alias: ["bicarbonato"],
    tipo: "usda",
    fdc: "175040",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, baking soda».",
  },
  {
    nombre: "Polvo para hornear",
    alias: ["polvo de hornear"],
    tipo: "usda",
    fdc: "172805",
    estado: "revisado",
    nota: "ID de su bibliografía (SR Legacy, bajo en sodio). SR Legacy trae también 172803 (con sulfato de sodio y aluminio) y 172804 (solo fosfato).",
  },
  {
    nombre: "Cremor tártaro",
    alias: ["bitartrato de potasio"],
    tipo: "usda",
    fdc: "175041",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, cream of tartar». Su bibliografía usaba Branded 2425013, que solo trae potasio.",
  },
  {
    nombre: "Stevia",
    alias: ["estevia", "extracto de stevia"],
    tipo: "usda",
    fdc: "170679",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Sweetener, herbal extract powder from Stevia leaf».",
  },
  {
    nombre: "Levadura seca",
    alias: ["levadura", "levadura seca activa", "levadura instantanea"],
    tipo: "usda",
    fdc: "175043",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Leavening agents, yeast, baker's, active dry».",
  },
  {
    nombre: "Levadura fresca",
    alias: ["levadura prensada"],
    tipo: "usda",
    fdc: "175042",
    estado: "propuesto",
    nota: "SR Legacy «Leavening agents, yeast, baker's, compressed».",
  },
  {
    nombre: "Vinagre",
    alias: ["vinagre blanco", "vinagre de alcohol", "vinagre blanco destilado"],
    tipo: "usda",
    fdc: "172237",
    estado: "propuesto",
    nota: "SR Legacy «Vinegar, distilled».",
  },
  {
    nombre: "Fécula de maíz",
    alias: ["almidon de maiz", "maicena"],
    tipo: "usda",
    fdc: "169698",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cornstarch».",
  },
  {
    nombre: "Jarabe de glucosa",
    alias: ["glucosa liquida", "jarabe de maiz"],
    tipo: "usda",
    fdc: "168837",
    estado: "propuesto",
    nota: "SR Legacy «Syrups, corn, light».",
  },
  {
    nombre: "Goma xantan",
    alias: ["goma xantana", "xantana", "goma xanthan"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2285516)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 77.8,
      fib: 77.8,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 2890,
      vitc: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 9 g; ingredientes: xanthan gum). Branded no trae humedad ni cenizas. Otra etiqueta de goma xantan pura (2663656) da 10 g de proteína y 0 mg de sodio: los valores varían entre fabricantes.",
  },
  {
    nombre: "Maltodextrina",
    alias: ["maltodextrina de maiz"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2585907)",
    valores: { prot: 0, grasa: 0, cho: 94.6, azt: 3.57, na: 89 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 56 g; ingredientes: maltodextrin). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Dextrosa",
    alias: ["dextrosa monohidratada", "glucosa en polvo"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2412809)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 90,
      fib: 0,
      azt: 90,
      ca: 0,
      fe: 0,
      k: 0,
      na: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 20 g; ingredientes: dextrose). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Eritritol",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2617273)",
    valores: { prot: 0, grasa: 0, cho: 100, azt: 0, na: 0 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 12 g; ingredientes: organic erythritol). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Alulosa",
    alias: ["alulosa en polvo"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2652700)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 100,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      k: 0,
      na: 0,
      vitd: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 10 g; ingredientes: allulose). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Psyllium",
    alias: ["psilio", "cascara de psyllium"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2413270)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 80,
      fib: 80,
      azt: 0,
      ca: 0,
      fe: 0,
      k: 0,
      na: 200,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 5 g; ingredientes: psyllium husk powder). Branded no trae humedad ni cenizas.",
  },
  {
    nombre: "Sal nitral",
    alias: ["sal de nitro", "sal de cura", "sal curante", "sal de nitro- sal nitral"],
    tipo: "valores",
    ref: "USDA Branded (ID: 1777297)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 0,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 36200,
      vitc: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 0.8 g; ingredientes: salt, sodium nitrite 6.25%, red fd&c #3 dye 0.000079%). Branded no trae humedad ni cenizas. ID de su bibliografía. El porcentaje de nitrito cambia entre fabricantes: confirmar con la ficha.",
  },
  {
    nombre: "Ácido cítrico",
    alias: ["acido citrico anhidro"],
    tipo: "valores",
    ref: "USDA Branded (ID: 628368)",
    valores: { prot: 0, grasa: 0, cho: 0, na: 0 },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 1 g; ingredientes: citric acid, less than 2% silicon dioxide (anticaking)). Branded no trae humedad ni cenizas. ID de su bibliografía. La etiqueta declara 0 g de carbohidratos.",
  },
  {
    nombre: "Humo líquido",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2082239)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 0,
      fib: 0,
      azt: 0,
      ca: 0,
      fe: 0,
      na: 0,
      vitc: 0,
      sat: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 4.5 g; ingredientes: water, natural pecan smoke flavor, vinegar, molasses and caramel color). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Glutamato monosódico",
    alias: ["glutamato", "msg"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2449440)",
    valores: { prot: 0, grasa: 0, cho: 0, na: 12500 },
    estado: "propuesto",
    nota: "Etiqueta del fabricante (porción 1 g; ingredientes: monosodium glutamate). Branded no trae humedad ni cenizas. Por estequiometría (C5H8NO4Na·H2O) el sodio sería 12 285 mg.",
  },
  {
    nombre: "Almidón de papa",
    alias: ["fecula de papa"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2671914)",
    valores: {
      prot: 0,
      grasa: 0,
      cho: 83.3,
      fib: 0,
      azt: 0,
      ca: 17,
      fe: 0,
      k: 58,
      na: 0,
      vitd: 0,
      sat: 0,
      trans: 0,
      col: 0,
    },
    estado: "revisado",
    nota: "Etiqueta del fabricante (porción 12 g; ingredientes: potato starch). Branded no trae humedad ni cenizas. ID de su bibliografía.",
  },
  {
    nombre: "Benzoato de sodio",
    alias: ["benzoato"],
    tipo: "valores",
    ref: "Estequiometría: C7H5NaO2 (144,10 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 15954,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 36.77,
      cho: 63.23,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Sorbato de potasio",
    alias: ["sorbato"],
    tipo: "valores",
    ref: "Estequiometría: C6H7KO2 (150,22 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 26028,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 46.0,
      cho: 54.0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como K2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Nitrito de sodio",
    alias: ["nitrito"],
    tipo: "valores",
    ref: "Estequiometría: NaNO2 (69,00 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 33321,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas no estimadas (se descompone al incinerar).",
  },
  {
    nombre: "Metabisulfito de sodio",
    alias: ["metabisulfito"],
    tipo: "valores",
    ref: "Estequiometría: Na2S2O5 (190,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 24188,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 74.72,
      cho: 25.28,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2SO4; carbohidratos por diferencia.",
  },
  {
    nombre: "Propionato de calcio",
    alias: ["propionato"],
    tipo: "valores",
    ref: "Estequiometría: Ca(C3H5O2)2 (186,22 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 21522,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 53.75,
      cho: 46.25,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como CaCO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Lactato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: NaC3H5O3 (112,06 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 20516,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 47.29,
      cho: 52.71,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. El lactato de sodio se vende como solución al 60 %: multiplicar por 0,6 o cargar la ficha.",
  },
  {
    nombre: "Diacetato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: NaH(C2H3O2)2 (142,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 16180,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 37.3,
      cho: 62.7,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Eritorbato de sodio",
    alias: ["eritorbato", "isoascorbato de sodio"],
    tipo: "valores",
    ref: "Estequiometría: C6H7NaO6·H2O (216,12 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 10638,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 24.52,
      cho: 75.48,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. Sin actividad de vitamina C declarada.",
  },
  {
    nombre: "Ascorbato de sodio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: C6H7NaO6 (198,11 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 88904,
      col: 0,
      na: 11605,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 26.75,
      cho: 73.25,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Ácido ascórbico",
    alias: ["vitamina c"],
    tipo: "valores",
    ref: "Estequiometría: C6H8O6 (176,12 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 100000,
      col: 0,
      na: 0,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 0,
      cho: 100,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Ácido orgánico: cenizas 0; carbohidratos por diferencia.",
  },
  {
    nombre: "Tripolifosfato de sodio",
    alias: ["tripolisfosfato de sodio", "tripolifosfato", "stpp"],
    tipo: "valores",
    ref: "Estequiometría: Na5P3O10 (367,86 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 31248,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Pirofosfato ácido de sodio",
    alias: ["sapp"],
    tipo: "valores",
    ref: "Estequiometría: Na2H2P2O7 (221,94 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 20718,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 91.88,
      cho: 8.12,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como NaPO3; carbohidratos por diferencia.",
  },
  {
    nombre: "Hexametafosfato de sodio",
    alias: ["hexametafosfato", "shmp"],
    tipo: "valores",
    ref: "Estequiometría: (NaPO3)n (101,96 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 22548,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Citrato de sodio",
    alias: ["citrato trisodico"],
    tipo: "valores",
    ref: "Estequiometría: Na3C6H5O7·2H2O (294,10 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 23451,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 54.06,
      cho: 45.94,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Cenizas como Na2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia. Dihidrato: el agua de cristalización no sale a 105 °C y queda en los carbohidratos por diferencia.",
  },
  {
    nombre: "Cloruro de potasio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: KCl (74,55 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 52447,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Cloruro de calcio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: CaCl2 anhidro (110,98 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 36113,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  {
    nombre: "Carbonato de calcio",
    alias: [],
    tipo: "valores",
    ref: "Estequiometría: CaCO3 (100,09 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 40044,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Sal inorgánica: cenizas = 100 %; carbohidratos por diferencia.",
  },
  // Ingredientes de su bibliografía, con los mismos ID.
  {
    nombre: "Harina de trigo",
    alias: [],
    tipo: "usda",
    fdc: "168896",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Wheat flour, white, bread, enriched».",
  },
  {
    nombre: "Margarina",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2058595); vitamina A y vitamina D: USDA FNDDS (ID: 2345737)",
    valores: {"prot": 0, "grasa": 78.6, "cho": 0, "fib": 0, "azt": 0, "ca": 0, "fe": 0, "na": 679, "vitc": 0, "sat": 14.3, "trans": 7140.0, "col": 0, "vita": 0, "vitd": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2058595): etiqueta Branded (porción 14 g).",
  },
  {
    nombre: "Queso cuajada",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2509858)",
    valores: {"prot": 17.9, "grasa": 25, "cho": 3.57, "fib": 0, "azt": 0, "ca": 618, "fe": 0, "k": 143, "na": 679, "sat": 16.1, "trans": 0, "col": 71},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2509858): etiqueta Branded (porción 28 g). El ID 2538718 no trae vitamina A.",
  },
  {
    nombre: "Canela molida",
    alias: [],
    tipo: "usda",
    fdc: "171320",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, cinnamon, ground».",
  },
  {
    nombre: "Anis",
    alias: [],
    tipo: "usda",
    fdc: "171316",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, anise seed».",
  },
  {
    nombre: "Clavo molido",
    alias: [],
    tipo: "usda",
    fdc: "171321",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, cloves, ground».",
  },
  {
    nombre: "Cardamomo",
    alias: [],
    tipo: "usda",
    fdc: "170919",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, cardamom».",
  },
  {
    nombre: "Jengibre en polvo",
    alias: ["jengibre"],
    tipo: "usda",
    fdc: "170926",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, ginger, ground».",
  },
  {
    nombre: "Tocino",
    alias: [],
    tipo: "usda",
    fdc: "168277",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Pork, cured, bacon, unprepared».",
  },
  {
    nombre: "Carne res",
    alias: [],
    tipo: "usda",
    fdc: "173086",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beef, New Zealand, imported, manufacturing beef, raw». Su fuente cita el NDB 23427, que en FDC es el ID 173086.",
  },
  {
    nombre: "Pimienta negra",
    alias: [],
    tipo: "usda",
    fdc: "170931",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, pepper, black».",
  },
  {
    nombre: "Paprika",
    alias: [],
    tipo: "usda",
    fdc: "171329",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, paprika».",
  },
  {
    nombre: "Cebolla en polvo",
    alias: [],
    tipo: "usda",
    fdc: "171327",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, onion powder».",
  },
  {
    nombre: "Tomate",
    alias: [],
    tipo: "usda",
    fdc: "170457",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Tomatoes, red, ripe, raw, year round average».",
  },
  {
    nombre: "Cebolla de huevo",
    alias: ["cebolla", "cebolla cabezona"],
    tipo: "usda",
    fdc: "170000",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Onions, raw».",
  },
  {
    nombre: "Cilantro",
    alias: [],
    tipo: "usda",
    fdc: "169997",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Coriander (cilantro) leaves, raw».",
  },
  {
    nombre: "Huevo",
    alias: [],
    tipo: "usda",
    fdc: "748967",
    estado: "revisado",
    nota: "ID de su bibliografía. Foundation «Eggs, Grade A, Large, egg whole».",
  },
  {
    nombre: "Harina de maíz blanca sin enriquecer",
    alias: [],
    tipo: "usda",
    fdc: "169696",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Corn flour, masa, unenriched, white».",
  },
  {
    nombre: "Café instataneo",
    alias: [],
    tipo: "usda",
    fdc: "171893",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beverages, coffee, instant, regular, powder».",
  },
  {
    nombre: "Salvado de trigo",
    alias: [],
    tipo: "usda",
    fdc: "169722",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Wheat bran, crude».",
  },
  {
    nombre: "Comino en polvo",
    alias: [],
    tipo: "usda",
    fdc: "170923",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, cumin seed».",
  },
  {
    nombre: "Oregano",
    alias: [],
    tipo: "usda",
    fdc: "171328",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, oregano, dried».",
  },
  {
    nombre: "Avena",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2503998)",
    valores: {"prot": 11.1, "grasa": 6.67, "cho": 68.9, "fib": 11.1, "azt": 0, "ca": 44, "fe": 4, "k": 0, "na": 0, "sat": 1.11, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2503998): etiqueta Branded (porción 45 iu); porción pequeña o en otra unidad: los valores por 100 g pueden ser imprecisos. El ID 2038206 no trae vitamina A.",
  },
  {
    nombre: "Aceite de canola",
    alias: ["aceite fritura"],
    tipo: "usda",
    fdc: "172336",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Oil, canola».",
  },
  {
    nombre: "Cocoa en polvo",
    alias: [],
    tipo: "usda",
    fdc: "169593",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cocoa, dry powder, unsweetened».",
  },
  {
    nombre: "Ajo crudo",
    alias: [],
    tipo: "usda",
    fdc: "169230",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Garlic, raw».",
  },
  {
    nombre: "Pimentón crudo",
    alias: [],
    tipo: "usda",
    fdc: "170108",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Peppers, sweet, red, raw».",
  },
  {
    nombre: "Cebolla larga",
    alias: [],
    tipo: "usda",
    fdc: "170005",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Onions, spring or scallions (includes tops and bulb), raw».",
  },
  {
    nombre: "Leche entera",
    alias: [],
    tipo: "usda",
    fdc: "746782",
    estado: "revisado",
    nota: "ID de su bibliografía. Foundation «Milk, whole, 3.25% milkfat, with added vitamin D».",
  },
  {
    nombre: "Carne de pecho, res",
    alias: [],
    tipo: "usda",
    fdc: "174740",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beef, New Zealand, imported, brisket navel end, separable lean and fat, raw».",
  },
  {
    nombre: "Perejil",
    alias: [],
    tipo: "usda",
    fdc: "170416",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Parsley, fresh».",
  },
  {
    nombre: "Carne molida de res",
    alias: [],
    tipo: "usda",
    fdc: "174030",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beef, ground, 90% lean meat / 10% fat, raw».",
  },
  {
    nombre: "Hierbabuena fresca",
    alias: [],
    tipo: "usda",
    fdc: "173474",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Peppermint, fresh».",
  },
  {
    nombre: "Espinaca",
    alias: [],
    tipo: "usda",
    fdc: "168462",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spinach, raw».",
  },
  {
    nombre: "Aji en polvo",
    alias: [],
    tipo: "usda",
    fdc: "171319",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, chili powder».",
  },
  {
    nombre: "Aceitunas",
    alias: [],
    tipo: "usda",
    fdc: "169096",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Olives, pickled, canned or bottled, green».",
  },
  {
    nombre: "Uvas pasas",
    alias: [],
    tipo: "usda",
    fdc: "168165",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Raisins, dark, seedless (Includes foods for USDA's Food Distribution Program)».",
  },
  {
    nombre: "Repollo",
    alias: [],
    tipo: "usda",
    fdc: "169975",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cabbage, raw».",
  },
  {
    nombre: "Apio",
    alias: [],
    tipo: "usda",
    fdc: "169988",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Celery, raw».",
  },
  {
    nombre: "Zanahoria",
    alias: [],
    tipo: "usda",
    fdc: "170393",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Carrots, raw».",
  },
  {
    nombre: "Salsa de soya",
    alias: [],
    tipo: "usda",
    fdc: "174278",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Soy sauce made from soy (tamari)».",
  },
  {
    nombre: "Fresa",
    alias: [],
    tipo: "usda",
    fdc: "167762",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Strawberries, raw».",
  },
  {
    nombre: "Arandanos (frescos)",
    alias: [],
    tipo: "usda",
    fdc: "171711",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Blueberries, raw».",
  },
  {
    nombre: "Mora (frescos)",
    alias: [],
    tipo: "usda",
    fdc: "173946",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Blackberries, raw».",
  },
  {
    nombre: "Durazno",
    alias: [],
    tipo: "usda",
    fdc: "169928",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Peaches, yellow, raw».",
  },
  {
    nombre: "Mango",
    alias: [],
    tipo: "usda",
    fdc: "169910",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Mangos, raw».",
  },
  {
    nombre: "Lulo",
    alias: [],
    tipo: "usda",
    fdc: "167790",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Naranjilla (lulo) pulp, frozen, unsweetened».",
  },
  {
    nombre: "Kiwi",
    alias: [],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2344734)",
    valores: {"hum": 83.9, "prot": 1.06, "grasa": 0.44, "cho": 14, "fib": 3, "azt": 8.99, "ca": 35, "fe": 0.24, "mg": 16, "k": 198, "na": 5, "zn": 0.14, "cu": 0.134, "vitc": 74.7, "vita": 4, "vitd": 0, "sat": 0.029, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2344734): FNDDS «Kiwi fruit, raw».",
  },
  {
    nombre: "Coco deshidratado",
    alias: [],
    tipo: "usda",
    fdc: "170170",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Nuts, coconut meat, dried (desiccated), not sweetened».",
  },
  {
    nombre: "Leche condensada",
    alias: [],
    tipo: "usda",
    fdc: "171275",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Milk, canned, condensed, sweetened».",
  },
  {
    nombre: "Coco natural pulpa",
    alias: [],
    tipo: "usda",
    fdc: "170169",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Nuts, coconut meat, raw».",
  },
  {
    nombre: "Laurel",
    alias: [],
    tipo: "usda",
    fdc: "170917",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, bay leaf».",
  },
  {
    nombre: "Curcuma",
    alias: [],
    tipo: "usda",
    fdc: "172231",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, turmeric, ground».",
  },
  {
    nombre: "Pollo molido",
    alias: ["pasta de pollo"],
    tipo: "usda",
    fdc: "171116",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Chicken, ground, raw».",
  },
  {
    nombre: "Papa cruda con cáscara",
    alias: [],
    tipo: "usda",
    fdc: "170026",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Potatoes, flesh and skin, raw».",
  },
  {
    nombre: "Azafran",
    alias: [],
    tipo: "usda",
    fdc: "170934",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, saffron».",
  },
  {
    nombre: "Habichuela",
    alias: [],
    tipo: "usda",
    fdc: "169961",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beans, snap, green, raw».",
  },
  {
    nombre: "Albahaca",
    alias: [],
    tipo: "usda",
    fdc: "171317",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, basil, dried».",
  },
  {
    nombre: "Vino",
    alias: [],
    tipo: "usda",
    fdc: "169070",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Alcoholic beverage, wine, cooking».",
  },
  {
    nombre: "Semola de trigo",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 1859669)",
    valores: {"prot": 10.7, "grasa": 1.79, "cho": 75, "fib": 3.6, "azt": 1.79, "ca": 0, "fe": 3.21, "na": 0, "vitc": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 1859669): etiqueta Branded (porción 56 g).",
  },
  {
    nombre: "Romero molido",
    alias: [],
    tipo: "usda",
    fdc: "171333",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, rosemary, dried».",
  },
  {
    nombre: "Tomillo",
    alias: [],
    tipo: "usda",
    fdc: "170938",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, thyme, dried».",
  },
  {
    nombre: "Semillas de mostaza",
    alias: [],
    tipo: "usda",
    fdc: "170929",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Spices, mustard seed, ground».",
  },
  {
    nombre: "Grasa de cerdo",
    alias: [],
    tipo: "usda",
    fdc: "167813",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Pork, fresh, separable fat, raw».",
  },
  {
    nombre: "Achiote",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2655209)",
    valores: {"prot": 0, "grasa": 0, "cho": 0, "na": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2655209): etiqueta Branded (porción 0.7 g); porción pequeña o en otra unidad: los valores por 100 g pueden ser imprecisos.",
  },
  {
    nombre: "Pierna de cerdo",
    alias: [],
    tipo: "usda",
    fdc: "169186",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Pork, Leg Cap Steak, boneless, separable lean and fat, raw».",
  },
  {
    nombre: "Harina de trigo integral",
    alias: [],
    tipo: "usda",
    fdc: "168944",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Wheat flour, whole-grain, soft wheat».",
  },
  {
    nombre: "Harina de arroz",
    alias: [],
    tipo: "usda",
    fdc: "169714",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Rice flour, white, unenriched».",
  },
  {
    nombre: "Sirope de caña",
    alias: [],
    tipo: "usda",
    fdc: "167743",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Syrup, Cane».",
  },
  {
    nombre: "Arequipe",
    alias: [],
    tipo: "usda",
    fdc: "173461",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Dulce de Leche».",
  },
  {
    nombre: "Queso mozarella",
    alias: [],
    tipo: "usda",
    fdc: "170845",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cheese, mozzarella, whole milk».",
  },
  {
    nombre: "Uchuva (seco)",
    alias: ["uchuva (seco"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2670392)",
    valores: {"prot": 6.67, "grasa": 1.67, "cho": 66.7, "fib": 16.7, "azt": 40, "ca": 30, "fe": 3.33, "k": 1830, "na": 0, "vita": 370, "vitd": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2670392): etiqueta Branded (porción 30 g).",
  },
  {
    nombre: "Mango (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2553621)",
    valores: {"prot": 0, "grasa": 0, "cho": 49.1, "fib": 5.3, "azt": 42.1, "ca": 0, "fe": 0, "k": 0, "na": 0, "sat": 0.19, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2553621): etiqueta Branded (porción 57 g). El ID 2428551 no trae vitamina A.",
  },
  {
    nombre: "Piña (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2072745)",
    valores: {"prot": 2.5, "grasa": 0, "cho": 75, "fib": 5, "azt": 52.5, "ca": 100, "fe": 0.9, "na": 0, "vitc": 7.5, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2072745): etiqueta Branded (porción 40 g). El ID 2423050 no trae vitamina D.",
  },
  {
    nombre: "Arandano (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2709202); grasa trans: USDA Branded (ID: 2634473)",
    valores: {"prot": 0.17, "grasa": 1.09, "cho": 82.8, "hum": 15.79, "azt": 72.56, "fib": 5.3, "ca": 9, "fe": 0.39, "mg": 4, "k": 49, "na": 5, "zn": 0.1, "cu": 0.063, "vita": 2, "vitd": 0, "vitc": 0.2, "col": 0, "sat": 0.088, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2709202): FNDDS «Cranberries, dried».",
  },
  {
    nombre: "Mora (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2608490); vitamina A: USDA (ID: 173946)",
    valores: {"prot": 6.67, "grasa": 0, "cho": 86.7, "fib": 20, "azt": 53.3, "ca": 200, "fe": 1.33, "k": 867, "na": 0, "vitc": 40, "vitd": 0, "sat": 0, "trans": 0, "col": 0, "vita": 11.0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2608490): etiqueta Branded (porción 15 g).",
  },
  {
    nombre: "Fresa (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2435656); vitamina A: USDA (ID: 167762)",
    valores: {"prot": 7.14, "grasa": 0, "cho": 78.6, "fib": 21.4, "azt": 50, "ca": 171, "fe": 7.14, "k": 1620, "na": 7, "sat": 0, "trans": 0, "col": 0, "vita": 1.0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2435656): etiqueta Branded (porción 14 g).",
  },
  {
    nombre: "Flor de jamaica (seco)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2408669)",
    valores: {"prot": 0, "grasa": 0, "cho": 20, "fib": 0, "azt": 0, "ca": 520, "fe": 21.6, "k": 0, "na": 0, "vitc": 48, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2408669): etiqueta Branded (porción 5 g).",
  },
  {
    nombre: "Costilla de cerdo",
    alias: [],
    tipo: "usda",
    fdc: "167895",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Pork, fresh, loin, country-style ribs, separable lean and fat, raw».",
  },
  {
    nombre: "Condimento jamon",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2056119)",
    valores: {"prot": 16.7, "grasa": 0, "cho": 50, "fib": 0, "azt": 0, "ca": 0, "fe": 0, "na": 13200, "vitc": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2056119): etiqueta Branded (porción 6 g). El ID 2397900 no trae vitamina D.",
  },
  {
    nombre: "Leche entera en polvo",
    alias: [],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2705585); grasa trans: USDA Branded (ID: 2489423)",
    valores: {"prot": 36.16, "grasa": 0.77, "cho": 51.98, "hum": 3.16, "azt": 51.98, "fib": 0, "ca": 1257, "fe": 0.32, "mg": 110, "k": 1794, "na": 535, "zn": 4.08, "cu": 0.041, "vita": 653, "vitd": 11, "vitc": 6.8, "col": 20, "sat": 0.499, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2705585): FNDDS «Milk, dry, not reconstituted».",
  },
  {
    nombre: "Crema de leche",
    alias: [],
    tipo: "usda",
    fdc: "170859",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cream, fluid, heavy whipping».",
  },
  {
    nombre: "Aceite de palma",
    alias: [],
    tipo: "usda",
    fdc: "171015",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Oil, palm».",
  },
  {
    nombre: "Platano verde",
    alias: [],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2709560); grasa trans: USDA Branded (ID: 2678742)",
    valores: {"prot": 1.3, "grasa": 0.35, "cho": 31.89, "hum": 65.2, "azt": 17.51, "fib": 1.7, "ca": 3, "fe": 0.55, "mg": 36, "k": 487, "na": 4, "zn": 0.19, "cu": 0.074, "vita": 56, "vitd": 0, "vitc": 18.4, "col": 0, "sat": 0, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2709560): FNDDS «Plantain, raw». Su fuente cita el código FNDDS 71905000, que en FDC es el ID 2709560.",
  },
  {
    nombre: "Pure de manzana",
    alias: [],
    tipo: "valores",
    ref: "USDA (ID: 172278); grasa trans: USDA Branded (ID: 2098852)",
    valores: {"hum": 89.5, "prot": 0.0, "grasa": 0.0, "sat": 0.0, "azt": 8.48, "fib": 1.7, "cen": 0.2, "cho": 10.3, "vita": 0.0, "vitd": 0.0, "vitc": 37.8, "col": 0.0, "na": 1.0, "k": 77.0, "ca": 5.0, "zn": 0.04, "fe": 0.22, "cu": 0.035, "mg": 3.0, "n": 0.0, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA (ID: 172278): SR Legacy «Babyfood, fruit, applesauce, junior».",
  },
  {
    nombre: "Glucosa",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 1918585)",
    valores: {"prot": 0, "grasa": 0, "cho": 45.4, "fib": 0, "azt": 45.4, "ca": 0, "fe": 0, "na": 15, "vitc": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 1918585): etiqueta Branded (porción 33 g).",
  },
  {
    nombre: "Harina de maiz amarillo",
    alias: [],
    tipo: "usda",
    fdc: "169695",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Corn flour, yellow, degermed, unenriched».",
  },
  {
    nombre: "Bocadillo de guayaba",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2668028)",
    valores: {"prot": 0, "grasa": 0, "cho": 76.7, "fib": 3.3, "azt": 70, "ca": 0, "fe": 0, "k": 157, "na": 0, "vitd": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2668028): etiqueta Branded (porción 30 g). El ID 2076301 no trae vitamina A.",
  },
  {
    nombre: "Mantequilla",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2103635)",
    valores: {"prot": 0, "grasa": 78.6, "cho": 0, "azt": 7.14, "ca": 71, "fe": 1.29, "na": 600, "vitc": 0, "sat": 57.1, "trans": 0, "col": 243},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2103635): etiqueta Branded (porción 14 g). El ID 2378745 no trae vitamina D.",
  },
  {
    nombre: "Chontaduro",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2325255)",
    valores: {"grasa": 5.71, "cho": 30.7, "fib": 2.9, "azt": 0.71, "ca": 12, "fe": 0, "k": 8, "na": 271, "sat": 1.79, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2325255): etiqueta Branded (porción 140 g). El ID 2475384 no trae vitamina D. La vitamina A de su fuente viene de TCAC (C016) y no se incluye.",
  },
  {
    nombre: "Cacao puro",
    alias: [],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2705587); grasa trans: USDA Branded (ID: 2600903)",
    valores: {"prot": 19.6, "grasa": 13.7, "cho": 57.9, "hum": 3, "azt": 1.75, "fib": 37, "ca": 128, "fe": 13.86, "mg": 499, "k": 1524, "na": 21, "zn": 6.81, "cu": 3.788, "vita": 0, "vitd": 0, "vitc": 0, "col": 0, "sat": 8.07, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2705587): FNDDS «Cocoa powder, not reconstituted».",
  },
  {
    nombre: "Manteca de cacao",
    alias: [],
    tipo: "valores",
    ref: "USDA (ID: 171421); grasa trans: USDA (ID: 173600)",
    valores: {"hum": 0.0, "prot": 0.0, "grasa": 100.0, "sat": 59.7, "azt": 0.0, "fib": 0.0, "cen": 0.0, "cho": 0.0, "vita": 0.0, "vitc": 0.0, "col": 0.0, "na": 0.0, "k": 0.0, "ca": 0.0, "zn": 0.0, "fe": 0.0, "cu": 0.0, "mg": 0.0, "mn": 0.0, "n": 0.0, "trans": 0.0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA (ID: 171421): SR Legacy «Oil, cocoa butter». El ID 173600 no trae vitamina D.",
  },
  {
    nombre: "Mezcla de frutos secos",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2653093); vitamina A: USDA (ID: 170162)",
    valores: {"prot": 20, "grasa": 36.7, "cho": 36.7, "fib": 6.7, "azt": 6.67, "ca": 67, "fe": 2, "k": 633, "na": 433, "vitd": 0, "sat": 3.33, "trans": 0, "col": 0, "vita": 0.0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2653093): etiqueta Branded (porción 30 g).",
  },
  {
    nombre: "Remolacha",
    alias: [],
    tipo: "usda",
    fdc: "169145",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beets, raw».",
  },
  {
    nombre: "Vinagre de manzana",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2656973)",
    valores: {"prot": 0, "grasa": 0, "cho": 0, "fib": 0, "azt": 0, "ca": 0, "fe": 0, "k": 0, "na": 0, "vitc": 0, "vita": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2656973): etiqueta Branded (porción 15 mlt).",
  },
  {
    nombre: "Pasta de ajo",
    alias: ["ajo pasta"],
    tipo: "valores",
    ref: "USDA Branded (ID: 454456); vitamina D: USDA Branded (ID: 2603033)",
    valores: {"prot": 0, "grasa": 0, "cho": 12.5, "fib": 0, "azt": 12.5, "ca": 0, "fe": 5.62, "na": 156, "vitc": 18.8, "sat": 0, "col": 0, "vitd": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 454456): etiqueta Branded (porción 16 g). El ID 2603033 no trae azúcar añadido.",
  },
  {
    nombre: "Limon",
    alias: [],
    tipo: "usda",
    fdc: "167747",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Lemon juice, raw».",
  },
  {
    nombre: "Champiñones crudos",
    alias: [],
    tipo: "usda",
    fdc: "169382",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Mushrooms, enoki, raw».",
  },
  {
    nombre: "Queso parmesano",
    alias: [],
    tipo: "usda",
    fdc: "325036",
    estado: "revisado",
    nota: "ID de su bibliografía. Foundation «Cheese, parmesan, grated».",
  },
  {
    nombre: "Salsa bechamel",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 484162)",
    valores: {"prot": 0, "grasa": 0, "cho": 76.9, "fib": 0, "azt": 0, "na": 1770, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 484162): etiqueta Branded (porción 6.5 g). El ID 969565 no trae vitamina A.",
  },
  {
    nombre: "Piña cruda",
    alias: [],
    tipo: "usda",
    fdc: "169124",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Pineapple, raw, all varieties».",
  },
  {
    nombre: "Miga de pan seca",
    alias: [],
    tipo: "usda",
    fdc: "174928",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Bread, crumbs, dry, grated, plain».",
  },
  {
    nombre: "Te negro",
    alias: [],
    tipo: "usda",
    fdc: "174144",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Beverages, tea, black, ready to drink».",
  },
  {
    nombre: "Fruta del dragon (pitahaya)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2196028)",
    valores: {"prot": 1, "grasa": 0, "fib": 3, "azt": 8, "ca": 20, "fe": 0.72, "mg": 40, "k": 175, "na": 0, "vitc": 2.4, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2196028): etiqueta Branded (porción 100 g).",
  },
  {
    nombre: "Cultivo de yogurt",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2031052)",
    valores: {"prot": 0, "grasa": 0, "cho": 100, "fib": 0, "azt": 0, "ca": 0, "fe": 0, "na": 0, "vitc": 480, "sat": 0, "trans": 0, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 2031052): etiqueta Branded (porción 5 g).",
  },
  {
    nombre: "Piel de cerdo frita",
    alias: ["chicharron", "chicharr\u00f3n"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2705902); grasa trans: USDA Branded (ID: 1522597)",
    valores: {"prot": 61.3, "grasa": 31.3, "cho": 0, "hum": 1.8, "azt": 0, "fib": 0, "ca": 30, "fe": 0.88, "mg": 11, "k": 127, "na": 1818, "zn": 0.56, "cu": 0.094, "vita": 12, "vitd": 0, "vitc": 0.5, "col": 95, "sat": 11.37, "trans": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA FNDDS (ID: 2705902): FNDDS «Pork skin rinds».",
  },
  {
    nombre: "Salsa de mora (mermelada de mora)",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 1960790)",
    valores: {"prot": 0, "grasa": 0, "cho": 63.3, "azt": 63.3, "na": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. USDA Branded (ID: 1960790): etiqueta Branded (porción 30 g). El ID 2060795 no trae vitamina A ni vitamina D.",
  },
  {
    nombre: "Berenjena",
    alias: [],
    tipo: "usda",
    fdc: "169228",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Eggplant, raw».",
  },
  {
    nombre: "Rabano",
    alias: [],
    tipo: "usda",
    fdc: "169276",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Radishes, raw».",
  },
  {
    nombre: "Melon",
    alias: [],
    tipo: "usda",
    fdc: "169092",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Melons, cantaloupe, raw».",
  },
  {
    nombre: "Pepino cohombro",
    alias: [],
    tipo: "usda",
    fdc: "169225",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Cucumber, peeled, raw».",
  },
  // Ingredientes de uso común en panadería, cárnicos, lácteos y bebidas (fuera de su bibliografía).
  {
    nombre: "Azúcar blanca",
    alias: ["azucar", "azucar refinada", "azucar blanca refinada"],
    tipo: "usda",
    fdc: "169655",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Sugars, granulated».",
  },
  {
    nombre: "Azúcar morena",
    alias: ["azucar moreno"],
    tipo: "usda",
    fdc: "168833",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Sugars, brown».",
  },
  {
    nombre: "Azúcar pulverizada",
    alias: ["azucar glass", "azucar impalpable", "azucar en polvo"],
    tipo: "usda",
    fdc: "169656",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Sugars, powdered».",
  },
  {
    nombre: "Miel de abejas",
    alias: ["miel"],
    tipo: "usda",
    fdc: "169640",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Honey».",
  },
  {
    nombre: "Harina de trigo todo uso",
    alias: ["harina todo uso", "harina de trigo blanqueada"],
    tipo: "usda",
    fdc: "168894",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Wheat flour, white, all-purpose, enriched, bleached».",
  },
  {
    nombre: "Chocolate amargo",
    alias: ["chocolate 70%", "cobertura de chocolate amargo"],
    tipo: "usda",
    fdc: "170273",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chocolate, dark, 70-85% cacao solids».",
  },
  {
    nombre: "Chocolate semiamargo",
    alias: ["chips de chocolate", "cobertura de chocolate"],
    tipo: "usda",
    fdc: "167976",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Candies, semisweet chocolate».",
  },
  {
    nombre: "Esencia de vainilla",
    alias: ["extracto de vainilla", "vainilla"],
    tipo: "usda",
    fdc: "173471",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Vanilla extract».",
  },
  {
    nombre: "Manteca vegetal",
    alias: ["grasa vegetal"],
    tipo: "usda",
    fdc: "173584",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Shortening, vegetable, household, composite». Compuesto de mantecas vegetales de EE. UU.; la composición de ácidos grasos de una manteca colombiana puede diferir: preferir su ficha.",
  },
  {
    nombre: "Aceite de soya",
    alias: ["aceite de soja"],
    tipo: "usda",
    fdc: "171411",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Oil, soybean, salad or cooking».",
  },
  {
    nombre: "Aceite de girasol",
    alias: [],
    tipo: "usda",
    fdc: "171025",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Oil, sunflower, linoleic, (approx. 65%)».",
  },
  {
    nombre: "Aceite de oliva",
    alias: [],
    tipo: "usda",
    fdc: "171413",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Oil, olive, salad or cooking».",
  },
  {
    nombre: "Leche en polvo descremada",
    alias: ["leche descremada en polvo"],
    tipo: "usda",
    fdc: "170877",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Milk, dry, nonfat, regular, without added vitamin A and vitamin D».",
  },
  {
    nombre: "Suero de leche en polvo",
    alias: ["lactosuero en polvo", "suero dulce en polvo"],
    tipo: "usda",
    fdc: "171283",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Whey, sweet, dried».",
  },
  {
    nombre: "Lactosuero líquido",
    alias: ["suero de leche", "lactosuero"],
    tipo: "usda",
    fdc: "171282",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Whey, sweet, fluid».",
  },
  {
    nombre: "Mantequilla sin sal",
    alias: [],
    tipo: "usda",
    fdc: "173430",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Butter, without salt».",
  },
  {
    nombre: "Queso crema",
    alias: [],
    tipo: "usda",
    fdc: "173418",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Cheese, cream».",
  },
  {
    nombre: "Yogur natural",
    alias: ["yogurt natural", "yogur entero"],
    tipo: "usda",
    fdc: "171284",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Yogurt, plain, whole milk».",
  },
  {
    nombre: "Queso fresco",
    alias: ["queso campesino"],
    tipo: "usda",
    fdc: "172223",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Cheese, fresh, queso fresco».",
  },
  {
    nombre: "Queso blanco",
    alias: [],
    tipo: "usda",
    fdc: "172224",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Cheese, white, queso blanco».",
  },
  {
    nombre: "Leche descremada",
    alias: ["leche desnatada"],
    tipo: "usda",
    fdc: "171269",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)».",
  },
  {
    nombre: "Leche semidescremada",
    alias: ["leche semidesnatada"],
    tipo: "usda",
    fdc: "171267",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D».",
  },
  {
    nombre: "Proteína de suero en polvo",
    alias: ["proteina de suero", "whey protein"],
    tipo: "usda",
    fdc: "173180",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beverages, Protein powder whey based».",
  },
  {
    nombre: "Maní",
    alias: ["mani crudo", "cacahuate"],
    tipo: "usda",
    fdc: "172430",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Peanuts, all types, raw».",
  },
  {
    nombre: "Almendras",
    alias: ["almendra"],
    tipo: "usda",
    fdc: "170567",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Nuts, almonds».",
  },
  {
    nombre: "Nueces",
    alias: ["nuez", "nuez de nogal"],
    tipo: "usda",
    fdc: "170187",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Nuts, walnuts, english».",
  },
  {
    nombre: "Avena en hojuelas",
    alias: ["hojuelas de avena"],
    tipo: "usda",
    fdc: "173904",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Cereals, oats, regular and quick, not fortified, dry».",
  },
  {
    nombre: "Arroz blanco",
    alias: ["arroz"],
    tipo: "usda",
    fdc: "168877",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Rice, white, long-grain, regular, raw, enriched».",
  },
  {
    nombre: "Pechuga de pollo",
    alias: ["pechuga de pollo sin piel"],
    tipo: "usda",
    fdc: "171077",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw».",
  },
  {
    nombre: "Muslo de pollo",
    alias: ["contramuslo de pollo"],
    tipo: "usda",
    fdc: "173627",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chicken, broilers or fryers, dark meat, thigh, meat only, raw».",
  },
  {
    nombre: "Piel de pollo",
    alias: [],
    tipo: "usda",
    fdc: "171452",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chicken, broilers or fryers, skin only, raw».",
  },
  {
    nombre: "Hígado de pollo",
    alias: [],
    tipo: "usda",
    fdc: "171060",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chicken, liver, all classes, raw».",
  },
  {
    nombre: "Hígado de res",
    alias: [],
    tipo: "usda",
    fdc: "169451",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beef, variety meats and by-products, liver, raw».",
  },
  {
    nombre: "Carne de res magra",
    alias: ["res magra", "bola de res"],
    tipo: "usda",
    fdc: "171757",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beef, round, top round steak, boneless, separable lean only, trimmed to 0\" fat, all grades, raw».",
  },
  {
    nombre: "Grasa de res",
    alias: ["sebo de res"],
    tipo: "usda",
    fdc: "170193",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beef, variety meats and by-products, suet, raw».",
  },
  {
    nombre: "Lomo de cerdo",
    alias: [],
    tipo: "usda",
    fdc: "168230",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Pork, fresh, loin, whole, separable lean only, raw».",
  },
  {
    nombre: "Paleta de cerdo",
    alias: [],
    tipo: "usda",
    fdc: "167843",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Pork, fresh, shoulder, whole, separable lean and fat, raw».",
  },
  {
    nombre: "Tilapia",
    alias: ["mojarra roja"],
    tipo: "usda",
    fdc: "175176",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Fish, tilapia, raw».",
  },
  {
    nombre: "Trucha",
    alias: ["trucha arcoiris"],
    tipo: "usda",
    fdc: "173717",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Fish, trout, rainbow, farmed, raw».",
  },
  {
    nombre: "Atún en agua",
    alias: ["atun enlatado en agua"],
    tipo: "usda",
    fdc: "334194",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. Foundation «Fish, tuna, light, canned in water, drained solids».",
  },
  {
    nombre: "Camarón",
    alias: ["camaron crudo"],
    tipo: "usda",
    fdc: "175179",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Crustaceans, shrimp, raw».",
  },
  {
    nombre: "Sardinas en aceite",
    alias: [],
    tipo: "usda",
    fdc: "175139",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Fish, sardine, Atlantic, canned in oil, drained solids with bone».",
  },
  {
    nombre: "Clara de huevo",
    alias: [],
    tipo: "usda",
    fdc: "172183",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Egg, white, raw, fresh».",
  },
  {
    nombre: "Yema de huevo",
    alias: [],
    tipo: "usda",
    fdc: "172184",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Egg, yolk, raw, fresh».",
  },
  {
    nombre: "Huevo en polvo",
    alias: ["huevo entero en polvo"],
    tipo: "usda",
    fdc: "172188",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Egg, whole, dried».",
  },
  {
    nombre: "Mayonesa",
    alias: [],
    tipo: "usda",
    fdc: "171009",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Salad dressing, mayonnaise, regular».",
  },
  {
    nombre: "Salsa de tomate",
    alias: ["ketchup", "catsup"],
    tipo: "usda",
    fdc: "168556",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Catsup».",
  },
  {
    nombre: "Mostaza",
    alias: [],
    tipo: "usda",
    fdc: "172234",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Mustard, prepared, yellow».",
  },
  {
    nombre: "Jugo de naranja",
    alias: ["zumo de naranja"],
    tipo: "usda",
    fdc: "169098",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Orange juice, raw (Includes foods for USDA's Food Distribution Program)».",
  },
  {
    nombre: "Agua de coco",
    alias: [],
    tipo: "usda",
    fdc: "170174",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Nuts, coconut water (liquid from coconuts)».",
  },
  {
    nombre: "Jarabe de maíz alta fructosa",
    alias: ["jmaf", "jarabe de alta fructosa"],
    tipo: "usda",
    fdc: "169659",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Syrups, corn, high-fructose».",
  },
  {
    nombre: "Guayaba",
    alias: [],
    tipo: "usda",
    fdc: "173044",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Guavas, common, raw».",
  },
  {
    nombre: "Papaya",
    alias: [],
    tipo: "usda",
    fdc: "169926",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Papayas, raw».",
  },
  {
    nombre: "Banano",
    alias: ["banano maduro"],
    tipo: "usda",
    fdc: "173944",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Bananas, raw».",
  },
  {
    nombre: "Plátano maduro",
    alias: ["platano amarillo"],
    tipo: "usda",
    fdc: "169130",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Plantains, yellow, raw».",
  },
  {
    nombre: "Mandarina",
    alias: [],
    tipo: "usda",
    fdc: "169105",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Tangerines, (mandarin oranges), raw».",
  },
  {
    nombre: "Guanábana",
    alias: [],
    tipo: "usda",
    fdc: "167761",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Soursop, raw».",
  },
  {
    nombre: "Uchuva fresca",
    alias: ["uchuva"],
    tipo: "usda",
    fdc: "173043",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Groundcherries, (cape-gooseberries or poha), raw». SR Legacy trae solo 11 de los 23 componentes.",
  },
  {
    nombre: "Feijoa",
    alias: [],
    tipo: "usda",
    fdc: "168176",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Feijoa, raw».",
  },
  {
    nombre: "Pera",
    alias: [],
    tipo: "usda",
    fdc: "169118",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Pears, raw».",
  },
  {
    nombre: "Manzana",
    alias: ["manzana roja"],
    tipo: "usda",
    fdc: "171688",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)».",
  },
  {
    nombre: "Aguacate",
    alias: [],
    tipo: "usda",
    fdc: "171705",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Avocados, raw, all commercial varieties».",
  },
  {
    nombre: "Arveja verde",
    alias: ["arveja"],
    tipo: "usda",
    fdc: "170419",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Peas, green, raw».",
  },
  {
    nombre: "Maíz tierno",
    alias: ["mazorca", "maiz dulce"],
    tipo: "usda",
    fdc: "169998",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Corn, sweet, yellow, raw».",
  },
  {
    nombre: "Fríjol cargamanto",
    alias: [],
    tipo: "usda",
    fdc: "175189",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beans, cranberry (roman), mature seeds, raw».",
  },
  {
    nombre: "Fríjol rojo",
    alias: [],
    tipo: "usda",
    fdc: "173744",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Beans, kidney, red, mature seeds, raw».",
  },
  {
    nombre: "Lenteja",
    alias: ["lentejas"],
    tipo: "usda",
    fdc: "172420",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Lentils, raw».",
  },
  {
    nombre: "Garbanzo",
    alias: ["garbanzos"],
    tipo: "usda",
    fdc: "173756",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Chickpeas (garbanzo beans, bengal gram), mature seeds, raw».",
  },
  {
    nombre: "Yuca cruda",
    alias: ["yuca"],
    tipo: "usda",
    fdc: "169985",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Cassava, raw».",
  },
  {
    nombre: "Ñame",
    alias: [],
    tipo: "usda",
    fdc: "170071",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Yam, raw».",
  },
  {
    nombre: "Ahuyama cruda",
    alias: ["ahuyama", "zapallo"],
    tipo: "usda",
    fdc: "169295",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Squash, winter, butternut, raw».",
  },
  {
    nombre: "Brócoli",
    alias: [],
    tipo: "usda",
    fdc: "170379",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Broccoli, raw».",
  },
  {
    nombre: "Lechuga",
    alias: ["lechuga batavia"],
    tipo: "usda",
    fdc: "169248",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Lettuce, iceberg (includes crisphead types), raw».",
  },
  {
    nombre: "Pimienta de olor",
    alias: ["pimienta malagueta", "pimienta de jamaica", "pimienta guayabita", "pimienta dulce"],
    tipo: "usda",
    fdc: "171315",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Spices, allspice, ground».",
  },
  {
    nombre: "Nuez moscada",
    alias: [],
    tipo: "usda",
    fdc: "171326",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Spices, nutmeg, ground».",
  },
  {
    nombre: "Ajonjolí",
    alias: ["sesamo"],
    tipo: "usda",
    fdc: "170150",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Seeds, sesame seeds, whole, dried».",
  },
  {
    nombre: "Linaza",
    alias: [],
    tipo: "usda",
    fdc: "169414",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Seeds, flaxseed».",
  },
  {
    nombre: "Chía",
    alias: ["semillas de chia"],
    tipo: "usda",
    fdc: "170554",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Seeds, chia seeds, dried».",
  },
  {
    nombre: "Quinua",
    alias: ["quinoa"],
    tipo: "usda",
    fdc: "168874",
    estado: "propuesto",
    nota: "Propuesto: no está en su bibliografía. SR Legacy «Quinoa, uncooked».",
  },
  // Correcciones a su bibliografía (11-sep-2026).
  {
    nombre: "Pechuga de pavo",
    alias: ["pavo"],
    tipo: "usda",
    fdc: "171098",
    estado: "propuesto",
    nota: "Corrige su bibliografía (11-sep-2026): traía 2636349 con vitamina D del 2523078, que es una salchicha, y un 25230780 que no existe. SR Legacy «Turkey, whole, breast, meat only, raw».",
  },
  {
    nombre: "Panela",
    alias: ["panela en polvo", "panela pulverizada"],
    tipo: "valores",
    ref: "USDA Branded (ID: 1855187)",
    valores: {"prot": 0, "grasa": 0, "cho": 85.7, "fib": 0, "azt": 82.1, "ca": 36, "fe": 0.32, "na": 0, "vitc": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "propuesto",
    nota: "Su bibliografía usa TCAC 2018 (k033), que no se puede publicar. Aquí va la etiqueta Branded 1855187, que su fuente ya usaba para grasa saturada y trans. Sin humedad ni cenizas.",
  },
  {
    nombre: "Maracuyá",
    alias: ["maracuya"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2344743)",
    valores: {"hum": 72.93, "prot": 2.2, "grasa": 0.7, "cho": 23.38, "fib": 10.4, "azt": 11.2, "ca": 12, "fe": 1.6, "mg": 29, "k": 348, "na": 28, "zn": 0.1, "cu": 0.086, "vitc": 30, "vita": 64, "vitd": 0, "sat": 0.059, "col": 0},
    estado: "revisado",
    nota: "ID de su bibliografía. FNDDS «Passion fruit, raw». Antes este nombre caía en la entrada de CIQUAL.",
  },
  {
    nombre: "Pulpa de maracuyá",
    alias: ["pulpa de maracuya"],
    tipo: "usda",
    fdc: "169108",
    estado: "revisado",
    nota: "ID de su bibliografía. SR Legacy «Passion-fruit, (granadilla), purple, raw».",
  },
  {
    nombre: "Jengibre fresco",
    alias: ["raiz de jengibre"],
    tipo: "usda",
    fdc: "169231",
    estado: "propuesto",
    nota: "Su bibliografía da el mismo ID (170926, molido) a «jengibre» y a «JENGIBRE EN POLVO». SR Legacy 169231 «Ginger root, raw» es el fresco.",
  },
  {
    nombre: "Agua",
    alias: ["agua potable", "hielo"],
    tipo: "agua",
    estado: "revisado",
  },
  // Alimentos artesanales e industriales tipicos de Colombia (14-sep-2026).
  {
    nombre: "Morcilla",
    alias: ["rellena", "morcilla negra"],
    tipo: "usda",
    fdc: "171618",
    estado: "propuesto",
    nota: "SR Legacy \u00abBlood sausage\u00bb.",
  },
  {
    nombre: "Mortadela",
    alias: ["mortadella"],
    tipo: "usda",
    fdc: "174573",
    estado: "propuesto",
    nota: "SR Legacy \u00abMortadella, beef, pork\u00bb.",
  },
  {
    nombre: "Jam\u00f3n cocido",
    alias: ["jamon", "jamon cocido", "jamon en lonchas"],
    tipo: "usda",
    fdc: "167872",
    estado: "propuesto",
    nota: "SR Legacy \u00abPork, cured, ham, boneless, regular (~11% fat), roasted\u00bb. Gen\u00e9rico industrial, no distingue marca.",
  },
  {
    nombre: "Longaniza",
    alias: ["longaniza de cerdo"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2676764)",
    valores: {"prot": 17.1, "grasa": 22.9, "cho": 4.29, "fib": 0, "azt": 2.86, "ca": 29, "fe": 2.57, "na": 1200, "vitc": 0, "vita": 386, "sat": 10, "trans": 0, "col": 57},
    estado: "propuesto",
    nota: "Producto de marca (Cacique Inc., EE.UU.), no espec\u00edficamente colombiano: USDA no tiene longaniza colombiana. Revisar contra dato medido antes de aceptar.",
  },
  {
    nombre: "Kumis",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2670636)",
    valores: {"prot": 5.83, "grasa": 1.88, "cho": 11.7, "fib": 0, "azt": 11.7, "aza": 8.3, "ca": 146, "fe": 0, "k": 179, "na": 58, "vitd": 2, "sat": 1.25, "trans": 0, "col": 8},
    estado: "propuesto",
    nota: "Etiqueta Branded rotulada \u00abColombian Style\u00bb (Intermark Foods, EE.UU.); no hay gen\u00e9rico SR Legacy de kumis.",
  },
  {
    nombre: "Guarapo de ca\u00f1a",
    alias: ["jugo de ca\u00f1a", "guarapo"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2710606)",
    valores: {"hum": 79.65, "prot": 0, "grasa": 0, "cho": 20.17, "fib": 0, "azt": 20.17, "ca": 7, "fe": 0.1, "mg": 3, "k": 11, "na": 43, "zn": 0.02, "cu": 0.021, "vita": 0, "vitd": 0, "vitc": 0, "sat": 0, "col": 0},
    estado: "propuesto",
    nota: "FNDDS \u00abSugar cane beverage\u00bb: jugo de ca\u00f1a sin fermentar. El guarapo fermentado (con alcohol) no tiene fuente en USDA.",
  },
  {
    nombre: "Masarepa (harina de ma\u00edz precocida)",
    alias: ["harina precocida de ma\u00edz", "harina pan", "masa harina de arepa"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2596400)",
    valores: {"prot": 6.67, "grasa": 0, "cho": 83.3, "fib": 3.3, "azt": 0, "aza": 0, "ca": 3, "fe": 6.67, "k": 143, "na": 0, "vitd": 0, "sat": 0, "trans": 0, "col": 0},
    estado: "propuesto",
    nota: "Goya, harina de ma\u00edz blanco precocida para arepas; carbohidratos por diferencia.",
  },
  {
    nombre: "Harina de trigo leudante",
    alias: ["harina leudante", "harina con polvo de hornear"],
    tipo: "usda",
    fdc: "168895",
    estado: "propuesto",
    nota: "SR Legacy \u00abWheat flour, white, all-purpose, self-rising, enriched\u00bb.",
  },
  {
    nombre: "Harina de yuca",
    alias: ["harina de yuca entera"],
    tipo: "usda",
    fdc: "2512377",
    estado: "propuesto",
    nota: "Foundation \u00abFlour, cassava\u00bb: ra\u00edz entera molida, no confundir con el almid\u00f3n (ver \u00abAlmid\u00f3n de yuca\u00bb).",
  },
  {
    nombre: "Nibs de cacao",
    alias: ["cacao nibs", "trozos de cacao tostado"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2175642)",
    valores: {"prot": 7.14, "grasa": 35.7, "cho": 50, "fib": 28.6, "azt": 7.14, "ca": 71, "fe": 5.14, "mg": 343, "na": 107, "vitc": 0, "sat": 14.3, "trans": 0, "col": 0},
    estado: "propuesto",
    nota: "Marca (Foods Alive Inc.), cacao 100% org\u00e1nico tostado y triturado.",
  },
  // Productos terminados genericos (14-sep-2026).
  {
    nombre: "Yogur griego natural",
    alias: ["yogurt griego", "yogur griego"],
    tipo: "usda",
    fdc: "171304",
    estado: "propuesto",
    nota: "SR Legacy \u00abYogurt, Greek, plain, whole milk\u00bb.",
  },
  {
    nombre: "Kéfir de leche",
    alias: ["kefir", "kefir de leche"],
    tipo: "usda",
    fdc: "170904",
    estado: "propuesto",
    nota: "SR Legacy \u00abKefir, lowfat, plain, LIFEWAY\u00bb: es la \u00fanica referencia de k\u00e9fir en SR Legacy, con marca.",
  },
  {
    nombre: "Yogur bebible saborizado",
    alias: ["yogurt bebible", "yogur saborizado", "yogurt saborizado"],
    tipo: "usda",
    fdc: "171285",
    estado: "propuesto",
    nota: "SR Legacy \u00abYogurt, fruit, low fat, 10 grams protein per 8 ounce\u00bb.",
  },
  {
    nombre: "Galleta tipo soda",
    alias: ["galleta soda", "galleta salada", "crackers"],
    tipo: "usda",
    fdc: "172746",
    estado: "propuesto",
    nota: "SR Legacy \u00abCrackers, saltines (includes oyster, soda, soup)\u00bb.",
  },
  {
    nombre: "Galleta dulce tipo María",
    alias: ["galleta maria", "galleta dulce"],
    tipo: "usda",
    fdc: "174971",
    estado: "propuesto",
    nota: "SR Legacy \u00abCookies, sugar, commercially prepared, regular (includes vanilla)\u00bb.",
  },
  {
    nombre: "Galleta rellena",
    alias: ["galleta con relleno", "galleta sandwich"],
    tipo: "usda",
    fdc: "172737",
    estado: "propuesto",
    nota: "SR Legacy \u00abCookies, vanilla sandwich with creme filling\u00bb.",
  },
  {
    nombre: "Ponqué",
    alias: ["ponque", "magdalena", "cupcake"],
    tipo: "usda",
    fdc: "172704",
    estado: "propuesto",
    nota: "SR Legacy \u00abCake, pound, commercially prepared, butter\u00bb.",
  },
  {
    nombre: "Papas fritas",
    alias: ["papas chips", "chips de papa"],
    tipo: "usda",
    fdc: "169677",
    estado: "propuesto",
    nota: "SR Legacy \u00abSnacks, potato chips, plain, salted\u00bb.",
  },
  {
    nombre: "Extruido de maíz salado",
    alias: ["fritos", "chitos", "snack de maiz"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2708198)",
    valores: {"prot": 6.17, "grasa": 33.36, "cho": 57.27, "hum": 1.07, "azt": 0.27, "fib": 4, "ca": 138, "fe": 1.2, "mg": 72, "k": 144, "na": 514, "zn": 1.29, "cu": 0.101, "vita": 3, "vitd": 0, "vitc": 0, "sat": 4.331, "col": 0},
    estado: "propuesto",
    nota: "FNDDS \u00abCorn chips, plain (Fritos)\u00bb.",
  },
  {
    nombre: "Maní salado",
    alias: ["mani salado", "cacahuate salado"],
    tipo: "usda",
    fdc: "172431",
    estado: "propuesto",
    nota: "SR Legacy \u00abPeanuts, spanish, oil-roasted, with salt\u00bb.",
  },
  {
    nombre: "Palomitas de maíz",
    alias: ["crispetas", "canguil", "popcorn"],
    tipo: "usda",
    fdc: "167959",
    estado: "propuesto",
    nota: "SR Legacy \u00abSnacks, popcorn, air-popped\u00bb.",
  },
  {
    nombre: "Salchicha tipo viena",
    alias: ["salchicha", "frankfurter", "salchicha frankfurter"],
    tipo: "usda",
    fdc: "171633",
    estado: "propuesto",
    nota: "SR Legacy \u00abFrankfurter, meat and poultry, cooked, boiled\u00bb.",
  },
  {
    nombre: "Tocineta",
    alias: ["bacon", "tocino"],
    tipo: "usda",
    fdc: "168322",
    estado: "propuesto",
    nota: "SR Legacy \u00abPork, cured, bacon, pre-sliced, cooked, pan-fried\u00bb.",
  },
  {
    nombre: "Nuggets de pollo",
    alias: ["nuggets"],
    tipo: "usda",
    fdc: "172111",
    estado: "propuesto",
    nota: "SR Legacy \u00abChicken, nuggets, dark and white meat, precooked, frozen, not reheated\u00bb.",
  },
  {
    nombre: "Pan blanco",
    alias: ["pan tajado", "pan de molde"],
    tipo: "usda",
    fdc: "174924",
    estado: "propuesto",
    nota: "SR Legacy \u00abBread, white, commercially prepared (includes soft bread crumbs)\u00bb.",
  },
  {
    nombre: "Pan integral",
    alias: ["pan de trigo integral"],
    tipo: "usda",
    fdc: "172688",
    estado: "propuesto",
    nota: "SR Legacy \u00abBread, whole-wheat, commercially prepared\u00bb.",
  },
  {
    nombre: "Croissant",
    alias: ["cruasan"],
    tipo: "usda",
    fdc: "174987",
    estado: "propuesto",
    nota: "SR Legacy \u00abCroissants, butter\u00bb.",
  },
  {
    nombre: "Dona",
    alias: ["donut", "rosquilla frita"],
    tipo: "usda",
    fdc: "174992",
    estado: "propuesto",
    nota: "SR Legacy \u00abDoughnuts, cake-type, plain, sugared or glazed\u00bb.",
  },
  {
    nombre: "Arepa",
    alias: ["arepa de maiz"],
    tipo: "usda",
    fdc: "168070",
    estado: "propuesto",
    nota: "SR Legacy \u00abRestaurant, Latino, arepa (unleavened cornmeal bread)\u00bb.",
  },
  {
    nombre: "Pandebono",
    alias: [],
    tipo: "valores",
    ref: "USDA Branded (ID: 2133418)",
    valores: {"prot": 12.9, "grasa": 14.3, "cho": 18.6, "fib": 1.4, "azt": 18.6, "ca": 329, "fe": 0.26, "na": 471, "vitc": 3.4, "sat": 10, "trans": 0, "col": 59},
    estado: "propuesto",
    nota: "Etiqueta Branded rotulada \u00abColombian Style\u00bb (Intermark Foods, EE.UU.). El fabricante reporta az\u00facares = carbohidratos totales (18,6 g ambos); puede ser un redondeo de etiqueta, no un dato aparte.",
  },
  // Consumo normal en Colombia, contra la canasta familiar del DANE (14-sep-2026).
  {
    nombre: "Arroz integral",
    alias: ["arroz integral crudo"],
    tipo: "usda",
    fdc: "169703",
    estado: "propuesto",
    nota: "SR Legacy \u00abRice, brown, long-grain, raw\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Cebada",
    alias: ["cebada perlada"],
    tipo: "usda",
    fdc: "170283",
    estado: "propuesto",
    nota: "SR Legacy \u00abBarley, hulled\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Salchichón",
    alias: ["salchichon"],
    tipo: "valores",
    ref: "USDA Branded (ID: 2150635)",
    valores: {"prot": 14, "grasa": 31.6, "cho": 1.75, "fib": 0, "azt": 0, "ca": 47, "fe": 1.75, "k": 191, "na": 667, "sat": 12.3, "trans": 0, "col": 79},
    estado: "propuesto",
    nota: "Etiqueta Branded (Intermark Foods, EE.UU.), rotulada \u00abSalchichon, cooked salami\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Helado",
    alias: ["helado de vainilla"],
    tipo: "usda",
    fdc: "167575",
    estado: "propuesto",
    nota: "SR Legacy \u00abIce creams, vanilla\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Gaseosa",
    alias: ["cola", "bebida gaseosa", "soda"],
    tipo: "usda",
    fdc: "174852",
    estado: "propuesto",
    nota: "SR Legacy \u00abBeverages, carbonated, cola, regular\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Bebida energizante",
    alias: ["energizante"],
    tipo: "usda",
    fdc: "173210",
    estado: "propuesto",
    nota: "SR Legacy \u00abBeverages, Energy drink, RED BULL\u00bb: \u00fanica referencia en SR Legacy, todas son de marca. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Leche de almendras",
    alias: ["bebida de almendras"],
    tipo: "usda",
    fdc: "174832",
    estado: "propuesto",
    nota: "SR Legacy \u00abBeverages, almond milk, unsweetened, shelf stable\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Caldo concentrado",
    alias: ["caldo de gallina", "cubo de caldo", "consomé"],
    tipo: "usda",
    fdc: "171562",
    estado: "propuesto",
    nota: "SR Legacy \u00abSoup, chicken broth or bouillon, dry\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Gelatina lista para comer",
    alias: ["gelatina de sabor", "gelatina preparada"],
    tipo: "usda",
    fdc: "169596",
    estado: "propuesto",
    nota: "SR Legacy \u00abGelatin desserts, dry mix, prepared with water\u00bb: distinta de \u00abGelatina sin sabor\u00bb (polvo puro sin sabor). Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Agua aromática",
    alias: ["aromática", "agua de hierbas", "infusión"],
    tipo: "usda",
    fdc: "173232",
    estado: "propuesto",
    nota: "SR Legacy \u00abBeverages, tea, herb, other than chamomile, brewed\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Uvas frescas",
    alias: ["uvas", "uva"],
    tipo: "usda",
    fdc: "174683",
    estado: "propuesto",
    nota: "SR Legacy \u00abGrapes, red or green (European type, such as Thompson seedless), raw\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  {
    nombre: "Agua mineral",
    alias: ["agua con gas", "agua embotellada"],
    tipo: "usda",
    fdc: "174158",
    estado: "propuesto",
    nota: "SR Legacy \u00abWater, bottled, generic\u00bb. Art\u00edculo de la canasta familiar del IPC (DANE).",
  },
  // Conservas, cereales, plant-based, confiteria y edulcorantes de mesa (14-sep-2026).
  {
    nombre: "Arveja enlatada",
    alias: ["arveja en lata", "arveja verde enlatada"],
    tipo: "usda",
    fdc: "170421",
    estado: "propuesto",
    nota: "SR Legacy \u00abPeas, green, canned, regular pack, solids and liquids\u00bb.",
  },
  {
    nombre: "Maíz enlatado",
    alias: ["choclo enlatado", "maiz en lata"],
    tipo: "usda",
    fdc: "169214",
    estado: "propuesto",
    nota: "SR Legacy \u00abCorn, sweet, yellow, canned, whole kernel, drained solids\u00bb.",
  },
  {
    nombre: "Durazno en almíbar",
    alias: ["durazno enlatado", "melocotón en almíbar"],
    tipo: "usda",
    fdc: "169112",
    estado: "propuesto",
    nota: "SR Legacy \u00abPeaches, canned, heavy syrup pack, solids and liquids\u00bb.",
  },
  {
    nombre: "Piña en almíbar",
    alias: ["piña enlatada"],
    tipo: "usda",
    fdc: "169944",
    estado: "propuesto",
    nota: "SR Legacy \u00abPineapple, canned, heavy syrup pack, solids and liquids\u00bb.",
  },
  {
    nombre: "Cereal de maíz (corn flakes)",
    alias: ["corn flakes", "cereal de maiz"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2708453)",
    valores: {"prot": 6.4, "grasa": 1.6, "cho": 79.52, "hum": 10.08, "azt": 9.44, "fib": 3.5, "ca": 4, "fe": 28.01, "mg": 29, "k": 128, "na": 703, "zn": 0.6, "cu": 0.069, "vita": 10, "vitd": 5, "vitc": 0, "sat": 0.198, "col": 0},
    estado: "propuesto",
    nota: "FNDDS \u00abCereal, corn flakes, plain\u00bb. El hierro es alto por fortificaci\u00f3n t\u00edpica del cereal.",
  },
  {
    nombre: "Granola",
    alias: ["granola casera", "cereal granola"],
    tipo: "usda",
    fdc: "171646",
    estado: "propuesto",
    nota: "SR Legacy \u00abCereals ready-to-eat, granola, homemade\u00bb.",
  },
  {
    nombre: "Leche de soya",
    alias: ["bebida de soya", "soymilk"],
    tipo: "usda",
    fdc: "172446",
    estado: "propuesto",
    nota: "SR Legacy \u00abSoymilk, original and vanilla, unfortified\u00bb.",
  },
  {
    nombre: "Tofu",
    alias: ["queso de soya"],
    tipo: "usda",
    fdc: "172448",
    estado: "propuesto",
    nota: "SR Legacy \u00abTofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)\u00bb.",
  },
  {
    nombre: "Hamburguesa vegetal",
    alias: ["veggie burger", "hamburguesa de soya"],
    tipo: "usda",
    fdc: "174287",
    estado: "propuesto",
    nota: "SR Legacy \u00abVeggie burgers or soyburgers, unprepared\u00bb.",
  },
  {
    nombre: "Proteína vegetal texturizada",
    alias: ["tvp", "carne vegetal texturizada", "soya texturizada"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2707451)",
    valores: {"prot": 51.1, "grasa": 3.33, "cho": 32.9, "hum": 6.24, "azt": 16.42, "fib": 17.5, "ca": 338, "fe": 7.34, "mg": 313, "k": 2480, "na": 2, "zn": 4.44, "cu": 1.51, "vita": 2, "vitd": 0, "vitc": 0, "sat": 0.136, "col": 0},
    estado: "propuesto",
    nota: "FNDDS \u00abTextured vegetable protein, dry\u00bb: sin hidratar.",
  },
  {
    nombre: "Caramelo duro",
    alias: ["dulce duro", "bombón duro"],
    tipo: "usda",
    fdc: "167990",
    estado: "propuesto",
    nota: "SR Legacy \u00abCandies, hard\u00bb.",
  },
  {
    nombre: "Chicle",
    alias: ["goma de mascar"],
    tipo: "usda",
    fdc: "168771",
    estado: "propuesto",
    nota: "SR Legacy \u00abChewing gum\u00bb.",
  },
  {
    nombre: "Chocolatina",
    alias: ["chocolate de leche", "barra de chocolate con leche"],
    tipo: "usda",
    fdc: "167587",
    estado: "propuesto",
    nota: "SR Legacy \u00abCandies, milk chocolate\u00bb.",
  },
  {
    nombre: "Refresco en polvo",
    alias: ["bebida en polvo saborizada", "jugo en polvo"],
    tipo: "valores",
    ref: "USDA FNDDS (ID: 2710613)",
    valores: {"prot": 0, "grasa": 1.01, "cho": 97.9, "hum": 0.52, "azt": 97.15, "fib": 0, "ca": 11, "fe": 0.17, "mg": 165, "k": 39, "na": 130, "zn": 0.03, "cu": 0.025, "vita": 0, "vitd": 0, "vitc": 40.6, "sat": 0.183, "col": 0},
    estado: "propuesto",
    nota: "FNDDS \u00abFruit flavored drink, powdered, not reconstituted\u00bb: polvo sin diluir.",
  },
  {
    nombre: "Sacarina",
    alias: ["edulcorante sacarina"],
    tipo: "usda",
    fdc: "169072",
    estado: "propuesto",
    nota: "SR Legacy \u00abSweeteners, tabletop, saccharin (sodium saccharin)\u00bb: producto de mesa, trae carga (dextrosa/maltodextrina), no sacarina pura.",
  },
  {
    nombre: "Aspartame",
    alias: ["edulcorante aspartame"],
    tipo: "usda",
    fdc: "169657",
    estado: "propuesto",
    nota: "SR Legacy \u00abSweeteners, tabletop, aspartame, EQUAL, packets\u00bb: producto de mesa, no aspartame puro.",
  },
  {
    nombre: "Sucralosa",
    alias: ["edulcorante sucralosa"],
    tipo: "usda",
    fdc: "170257",
    estado: "propuesto",
    nota: "SR Legacy \u00abSweeteners, tabletop, sucralose, SPLENDA packets\u00bb: producto de mesa, no sucralosa pura.",
  },
  // Aditivos por estequiometria, segundo grupo (14-sep-2026).
  {
    nombre: "Dióxido de titanio",
    alias: ["titanio dioxido", "TiO2"],
    tipo: "valores",
    ref: "Estequiometría: TiO2 (79,87 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 100,
      cho: 0,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; sin ficha técnica con tabla nutricional (los proveedores solo reportan pureza y especificación física). Pigmento inorgánico inerte: cenizas = 100%; carbohidratos por diferencia.",
  },
  {
    nombre: "Acesulfame de potasio",
    alias: ["acesulfame k", "acesulfamo de potasio"],
    tipo: "valores",
    ref: "Estequiometría: C4H4KNO4S (201,24 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 0,
      k: 19432,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 34.34,
      cho: 65.66,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL; compuesto puro sin humedad libre. Solo se encontró en un producto de marca ya mezclado con aspartame (no aplica). Cenizas como K2CO3 (residuo de una sal orgánica a 550 °C); carbohidratos por diferencia.",
  },
  {
    nombre: "Ciclamato de sodio",
    alias: ["ciclamato"],
    tipo: "valores",
    ref: "Estequiometría: C6H12NNaO3S (201,22 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 11426,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 26.34,
      cho: 73.66,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL (prohibido en EE.UU., por eso tampoco en FDC); compuesto puro sin humedad libre. Cenizas como Na2CO3; carbohidratos por diferencia.",
  },
  {
    nombre: "Tartrazina",
    alias: ["amarillo 5", "colorante tartrazina"],
    tipo: "valores",
    ref: "Estequiometría: C16H9N4Na3O9S2 (534,36 g/mol)",
    valores: {
      hum: 0,
      prot: 0,
      grasa: 0,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0,
      vita: 0,
      vitd: 0,
      vitc: 0,
      col: 0,
      na: 12906,
      k: 0,
      ca: 0,
      zn: 0,
      fe: 0,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 29.76,
      cho: 70.24,
    },
    estado: "propuesto",
    nota: "Sin fuente en USDA ni CIQUAL. Colorante azoico, no un carbohidrato real: el 70,24% de \u00abcarbohidratos por diferencia\u00bb es un residuo mecánico del método (masa no contabilizada como cenizas), no un aporte energético real — a diferencia de benzoato/sorbato, aquí ese residuo no tiene respaldo metabólico. Usar con esa advertencia. Cenizas como Na2CO3.",
  },
  // Ulluco, tabla peruana INS (14-sep-2026).
  {
    nombre: "Ulluco",
    alias: ["olluco", "papa lisa", "ruba"],
    tipo: "valores",
    ref: "INS Peru, Tablas Peruanas de Composicion de Alimentos, 8a ed. (2009), codigo U17 \u00abOlluco sin c\u00e1scara\u00bb",
    valores: {
      hum: 83.7,
      prot: 1.1,
      grasa: 0.1,
      sat: 0,
      trans: 0,
      azt: 0,
      fib: 0.8,
      vita: 5,
      vitd: 0,
      vitc: 11.5,
      col: 0,
      na: 0,
      k: 0,
      ca: 3,
      zn: 0,
      fe: 1.1,
      cu: 0,
      mg: 0,
      mn: 0,
      cen: 0.8,
      cho: 14.3,
    },
    estado: "propuesto",
    nota: "Tabla peruana (Ullucus tuberosus), no colombiana espec\u00edfica; el ulluco se consume en Nari\u00f1o y Boyac\u00e1 como el mismo cultivo. Vitamina A solo como retinol (sin equivalentes totales). Sin dato en la fuente: sodio, potasio, zinc, cobre, magnesio, manganeso, vitamina D (puestos en 0, no confirmados como aus\u00e9ntes). Licencia: reproducci\u00f3n total o parcial autorizada citando la fuente (R.J. N\u00b0 121-2008-OPD/INS).",
  },
];
